### ISSUE TITLE
Add GUID to actions

### ISSUE THREAD

**Issue by james-s-turner** [acdlite/redux-actions#10]
What do you think about adding a GUID field to each action to allow unique identification. This could be useful for:
1. Linking errors to the original actions that created them
2. Helping problem analysis in production systems after the fact
3. Tooling for time-travel development tools

You could put it into the meta property, but I think this could prove useful as a first class concept.

**Comment by jprichardson** [comment]
Why not just put this GUID in the payload? This seems like overengineering IMHO.

**Comment by james-s-turner** [comment]
Yes I take your point, however I think its more an issue of standardisation rather than over-engineering. It would allow people to automatically make use of tooling written by a third party. Imagine a time-travel tool (like the one demoed by Dan at the Paris React conference) used by a support team. You could get a log of all the actions and then play back to an action with a specific ID. The tool just looks inside the action for the well-known GUID property. 
It doesn't have to be a mandatory property - so if you think it's over-engineering then don't use it. But if you do want a GUID give it a standard name and format.

**Comment by acdlite** [comment]
I think GUIDs are a good idea but they should be handled by a separate middleware further down the chain.
