### ISSUE TITLE
ESLint doesn't understand object spread syntax

### ISSUE THREAD

**Issue by yangmillstheory** [acdlite/redux-actions#100]
We can write code that uses this feature with passing tests, but ESLint complains.

To fix this, we need to use https://github.com/babel/babel-eslint.

**Comment by timche** [comment]
Yup, we could also rewrite our build process using npm `scripts` instead of the `Makefile`.

**Comment by yangmillstheory** [comment]
This would be great. Object spread is so useful.

**Comment by yangmillstheory** [comment]
This issue will be closed by https://github.com/acdlite/redux-actions/pull/107.
