### ISSUE TITLE
Parameter naming in createAction doesn't make sense

### ISSUE THREAD

**Issue by yangmillstheory** [acdlite/redux-actions#101]
Generally related to #47.

https://github.com/acdlite/redux-actions/blob/master/src/createAction.js#L5 calls the payload creator `actionCreator`, which is a very different thing.

Actually the [signature of `createAction` in the README](https://github.com/acdlite/redux-actions/blob/master/README.md#createactiontype-payloadcreator--identity-metacreator) spells out pretty clearly what this parameter should be called.

**Comment by timche** [comment]
Would you mind opening a PR to change this?

**Comment by yangmillstheory** [comment]
Closed in https://github.com/acdlite/redux-actions/commit/e7bdb2f6109ec196ce097bccd7026bf1497a1643.
