### ISSUE TITLE
Tests method names wrongly call payload creators "action creators"

### ISSUE THREAD

**Issue by yangmillstheory** [acdlite/redux-actions#103]
This adds to already confusing terminology (#47, #101).

The following lines should be changed to stop calling payload creators "action creators":

- https://github.com/acdlite/redux-actions/blob/master/src/__tests__/createAction-test.js#L120
- https://github.com/acdlite/redux-actions/blob/master/src/__tests__/createAction-test.js#L25

**Comment by timche** [comment]
This could be done together with resolving #101.

**Comment by yangmillstheory** [comment]
Closed in https://github.com/acdlite/redux-actions/commit/e7bdb2f6109ec196ce097bccd7026bf1497a1643.
