### ISSUE TITLE
no-reserved-keys rule

### ISSUE THREAD

**Issue by istarkov** [acdlite/redux-actions#11]
To prevent `no-reserved-keys` eslint rule error (which is on by default at a lot of companies) 
Every time i need to write in handleAction(s) something like this 

`// eslint-disable-line no-reserved-keys`

 or this 

```
...
  ['throw'](state, { payload }) { ...
...
```

may be it will be more likely to give an alias for throw like `error` , `onError` etc...

**Comment by acdlite** [comment]
I see your point, but I would prefer to keep calling it `throw` because it matches the ES6 generator interface.

**Comment by acdlite** [comment]
Oh wait you're suggesting an alias. Yeah let's think about that.

**Comment by johanneslumpe** [comment]
@acdlite how about `reject` ?

**Comment by acdlite** [comment]
I was thinking `onThrow()`.

**Comment by johanneslumpe** [comment]
I'm fine with both :) `reject()` is a tad shorter though :P

**Comment by istarkov** [comment]
+1 `reject()`

**Comment by acdlite** [comment]
Yeah it's shorter, but it's a totally different word :D It shouldn't seem like a different thing. And I would really prefer everyone use `throw()`, anyway.

**Comment by johanneslumpe** [comment]
I was just using it because for promises throw and reject are almost synonyms

**Comment by ekmartin** [comment]
Would be nice with an alias, even though I definitely see the point about keeping with the generator interface. Kind of painful to have to disable linting rules though.

**Comment by lukewestby** [comment]
@acdlite @johanneslumpe do we want to move forward with the alias?

**Comment by johanneslumpe** [comment]
@lukewestby I personally don't mind having an alias. I'm not really using this lib anymore though. I have resorted to just using arrow functions and implicit returns.

**Comment by timche** [comment]
Since this discussion hasn't come an result, I'll close it for now. Re-open if it will become necessary.
