### ISSUE TITLE
Documentation inconsistency - error.true not set anymore from createAction

### ISSUE THREAD

**Issue by Tzaphkiel** [acdlite/redux-actions#110]
In [createAction with payload Errror](https://github.com/acdlite/redux-actions/blob/master/README.md#createactiontype-payloadcreator--identity-metacreator) documentation, it is mentionned that the `action.error` will be set to `true`.
```js
const increment = createAction('INCREMENT');

const error = new TypeError('not a number');
expect(increment(error)).to.deep.equal({
  type: 'INCREMENT',
  payload: error,
  error: true
});
```
This [was the case](https://github.com/ngokevin/redux-actions/blob/13f436b00ff30964aaaa71c82354496f4da0071f/src/createAction.js#L18) but is [not anymore (master)](https://github.com/ngokevin/redux-actions/blob/master/src/createAction.js)

It seems to have been lost somehow from this [commit](https://github.com/ngokevin/redux-actions/commit/13f436b00ff30964aaaa71c82354496f4da0071f) 

Either the documentation has to be **adapted** or the **feature restored**.

**Comment by timche** [comment]
Thanks for reporting this issue @Tzaphkiel. Can you please give an example how you create the actions? The tests are running fine, but I would like to know how we can reproduce this.

**Comment by Tzaphkiel** [comment]
Hi,

if you mention these [tests](https://github.com/ngokevin/redux-actions/blob/master/src/__tests__/createAction-test.js), 
they do not seem to test the Error setting as a payload as was done before [here](https://github.com/ngokevin/redux-actions/blob/13f436b00ff30964aaaa71c82354496f4da0071f/src/__tests__/createAction-test.js#L55)

**Comment by timche** [comment]
I am referring to these tests: https://github.com/acdlite/redux-actions/blob/master/src/__tests__/createAction-test.js#L51-L83

**Comment by Tzaphkiel** [comment]
Apologies, I linked the wrong repository...

An example usage would be : 
```coffee
checkStatus = (response) ->
  code  = response?.status
  throw new Error("Data not found") if code is 404
  unless code < 400
    throw new RangeError "Request failed with error code #{code}"

nodeDataLoaded = (data) ->
  if not data
    {type: ActionTypes.LOAD_NODE_DATA}
  else
    createAction(ActionTypes.LOAD_NODE_DATA)(data)

fetchNavNodeData = (id) ->
  (dispatch, getState) ->
    fetch(serverEndpoint + "/nav/#{instance}/#{id}", {headers: {accept: 'application/json'}})
        .then((response) ->
          checkStatus response
          response.json())
        .then((data) ->
          dispatch nodeDataLoaded(data))
        .catch( (error) -> dispatch nodeDataLoaded(error))
```

**Comment by timche** [comment]
> I'm using an npm dependency: "redux-action": "1.0.0"

There is the problem. Our library is called redux-action**s**. You are using the wrong library ;)

**Comment by Tzaphkiel** [comment]
Will update and check again. thx.

**Comment by Tzaphkiel** [comment]
It works much better with the proper one...
![image](https://cloud.githubusercontent.com/assets/644489/16948578/cab7efc0-4db5-11e6-850a-2a4922217fba.png)

Thank you... it did seem strange the documentation was not in sync with the code.
