### ISSUE TITLE
null Payload

### ISSUE THREAD

**Issue by arb** [acdlite/redux-actions#118]
Looking at https://github.com/acdlite/redux-actions/blob/master/src/createAction.js#L16-L18 it now seems impossible to set an action payload to `null` or `undefined`?

Or am I missing something?

**Comment by yangmillstheory** [comment]
@arb You might want to weigh in on #115.

**Comment by arb** [comment]
Looks like someone is already trying to deal with this. Thanks for the link.

**Comment by timche** [comment]
Just for clarity: I must admit that it was indeed a bad decision. If we are going to do this, this will be definitely a breaking change that is coming with v1.0.0.
