### ISSUE TITLE
Multiple handlers per action

### ISSUE THREAD

**Issue by nd0ut** [acdlite/redux-actions#12]
How about this?
```javascript
const reducer = handleActions({
  SELECT_PRODUCT: [select, setColor],
  UNSELECT_PRODUCT: [unselect, unsetColor]
}, initialState);
```

**Comment by lukewestby** [comment]
@nd0ut how would these functions be called? In your example, would the value of `select()` then be passed to `setColor()` and then returned?

**Comment by lukewestby** [comment]
@nd0ut I'm going to close this for now, and offer a suggestion:

If you would like to compose several functions for use as a single reducer you can use `_.flow()` or `_.flowRight()` from lodash to accomplish this, depending on the order you'd like them to be called.

- https://lodash.com/docs#flow
- https://lodash.com/docs#flowRight

```js
import { flow } from 'lodash';
const reducer = handleActions({
  SELECT_PRODUCT: flow(select, setColor),
  UNSELECT_PRODUCT: flow(unselect, unsetColor)
}, initialState);
```
