### ISSUE TITLE
lodash dependency

### ISSUE THREAD

**Issue by arb** [acdlite/redux-actions#120]
Looking through the code, the majority of lodash usage is extremely basic, most of it is just things like `isFunction` and `isObject`. I'm curious if there has been any discussion about dropping the lodash dependency entirely? Seems like a pretty large burden just for basic type checking functions.

**Comment by timche** [comment]
So why should it be an issue? Using these functions gives us safety that they just work.

**Comment by arb** [comment]
Size of bundle and depedency management is my most "scientific" reason. The large project I'm working on now does not use lodash anywhere, but it's included in our bundle because this library uses it.

On a personal level, I don't think this project really needs lodash as all of the used lodash features are basically one-liners; especially since you're using babel so have access to all the fancy ES6 features.

**Comment by timche** [comment]
We are only cherry-picking the functions we need with the [slash import](https://github.com/acdlite/redux-actions/blob/master/src/handleAction.js#L1-L4), so in the end, only required functions are in the bundle and not the whole `lodash` library.

Indeed there are some functions like [`isArray`](https://github.com/acdlite/redux-actions/blob/master/src/createActions.js#L4) we could replace with their ES5/ES6 equivalent, but not all (for example [`camelCase`](https://github.com/acdlite/redux-actions/blob/master/src/createActions.js#L2)).

We might rewrite some stuff to drop some unnecessary `lodash` functions.

**Comment by arb** [comment]
It's true that doing the slash import keeps the amount of lodash code to a smaller amount, those requires STILL bring with them a fair amount of common lodash code so that those imports need.

**Comment by timche** [comment]
I've just seen that [Redux is also using lodash](https://github.com/reactjs/redux/search?utf8=%E2%9C%93&q=lodash). So lodash will be installed and bundled anyway if you are using Redux in your project.

Imo lodash has also become a standard library and as I said above, it gives us safety that things are working. It is also known to be performant out of the box and makes the code more readable, so I don't think that we are dropping lodash completely except for the things that can also be written natively.

**Comment by arb** [comment]
I didn't realize redux was using it; bummer. Well with that in mind it would make sense to leave lodash in since it's already sort of part of the ecosystem.
