### ISSUE TITLE
Identity function with createAction cause an error with redux-dev-tools

### ISSUE THREAD

**Issue by gaelduplessix** [acdlite/redux-actions#121]
If I a create a basic action with `createAction` that doesn't handle any payload, it will use the identity function:
```js
const increment = createAction('INCREMENT')
// increment(42) => { type: 'INCREMENT', payload: 42 }
```

However, when using redux with react, you often connect your actions creators using `mapDispatchToProps`, like:
```js
const myContainer = connect(mapStateToPros, { increment })(myComponent)
```

And then in your component, you directly pass your event to a react event such as:
```js
const component = ({ increment }) => (
    <button onClick={increment}>Click me !</button>
)
```

Thus, when react will call our action, it will be called with the `SyntheticEvent` generated by the `onClick` event as parameter. This event object will end-up in our payload:
```js
// Dispatched action:
{
  type: 'INCREMENT',
  payload: // React pooled event, cf: https://facebook.github.io/react/docs/events.html#event-pooling
}
```

So if we inspect our page with [redux-dev-tools](https://github.com/gaearon/redux-devtools), we get errors like:
```
warning.js:44 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `screenY` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.warning
```

To prevent this, we must prevent the original event from being added to the payload. Thus, I have to create my action like:
```js
const increment = createAction('INCREMENT', () => {}) // Provide a no-op function
```

I'm not really satisfied with this solution, adding a `no-op` function to any "basic" action that doesn't handle any payload is a bit obscure I think.

Any idea for a better way around this problem ? Maybe a "Note:" should be added in the docs to prevent others from encountering the same issue.

**Comment by timche** [comment]
We once had this issue reported in #90.

Here is my opinion to that: The only thing we can do is to write a FAQ/gotchas/common issues. I am not a friend of doing changes only for this special case where the action creator/identity function itself is still working like advertised. Imo it's up the developer to intercept those things.

**Comment by gaelduplessix** [comment]
I agree that this may not justify a breaking change.

Improving the doc is probably enough but do you have any solution better than doing `() => {}` ?

**Comment by timche** [comment]
You have 3 options:

1. Provide a no-op function in the action creator like you did to prevent passing the event, but then you can't pass any arguments to it.

2. Wrap a function around `increment`  in `mapDispatchToProps`, but then you to write a `mapDispatchToProps` function every time for prevent it.
```js
function mapDispatchToProps(dispatch) {
  return {
    increment: () => dispatch(increment())
  }
}
```

3. Wrap a function around `increment` in the component, when you know that you are passing it to an React event.
```js
 const component = ({ increment }) => (
    <button onClick={() => increment()}>Click me !</button>
)
```

Imo option 3 is a good tradeoff of effort, control and transparency.

**Comment by yangmillstheory** [comment]
I believe **3** will fail [this lint rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md).

I'm a big fan of **2**. 

This is exactly what `mapDispatchToProps` should be doing based on its name: fitting the action creators to `dispatch`. In this case it's sanitizing the arguments. More complicated mappers could curry the action creators with parameters from `ownProps` to keep the `propType` API of the component as small as possible, which is 👍.

**Comment by timche** [comment]
@yangmillstheory That lint rule will only fail for classes if I remember correctly. Any function inside that stateless function will a new function. If it should really fail, writing the function outside the jsx prop will resolve it, which is also better than what I've suggested in 3.

```js
const component = ({ increment }) => {
  handleOnClick = () => increment()
  return (
    <button onClick={handleOnClick}>Click me !</button>
  )
}
```

**Comment by yangmillstheory** [comment]
It actually fails for stateless functional components too:

```js
export function MyComponent({ callback }) {
  return <div onClick={ () => callback() }>Hello, World!</div>
}

MyComponent.propTypes = {
  callback: PropTypes.func.isRequired,
}
```


```
web_1  | ERROR in ./app/core/layer/message.js
web_1  |
web_1  | /var/www/arivale-coach-client/src/app/core/layer/message.js
web_1  |   33:15  error  JSX props should not use arrow functions  react/jsx-no-bind
web_1  |
web_1  | ✖ 1 problem (1 error, 0 warnings)
web_1  |
```

Passing a function-local reference to `onClick` does pass the rule though.

**Comment by macrozone** [comment]
just ran into it which froze react-native-debugger. Assuming identity function as default param is maybe not the best idea and can lead to this strange bugs. Not worth a breaking change, i agree. But something to re-consider if this library should ever get a new major version...
