### ISSUE TITLE
Can we safely drop the Symbols support?

### ISSUE THREAD

**Issue by timche** [acdlite/redux-actions#126]
With v1.0.0 we would also like to drop the Symbols support as they are not recommended and ["generally a bad idea"](https://github.com/acdlite/redux-actions/issues/20#issuecomment-134340125).

Before we are dropping it completely, is anyone using them extensively?

**Comment by yangmillstheory** [comment]
FYI [this is the original thread](https://github.com/acdlite/redux-actions/issues/20) where we decided to adopt Symbol support.

**Comment by theghostbel** [comment]
You can put somewhere a "patch" so anyone can adopt "Symbal" supoprt if they need it. I personally don't know any project who uses Symbols.

**Comment by JaKXz** [comment]
I'm curious to see if there are any use cases for Symbols before just dropping them. From the Redux docs:

> Note that it is okay to use Symbols, Promises, or other non-serializable values in an action if the action is intended for use by middleware. Actions only need to be serializable by the time they actually reach the store and are passed to the reducers.

but it might make _more_ sense for FSA to "standardize" on strings only for the [advantages mentioned](http://redux.js.org/docs/faq/Actions.html#why-should-type-be-a-string-or-at-least-serializable-why-should-my-action-types-be-constants).

**Comment by timche** [comment]
If we are unsure about it, I think it's okay to keep it. They don't do anything harmful.

**Comment by JaKXz** [comment]
@timche I agree - I think it makes a better candidate for the next major version to be dropped. We can mark it as deprecated for now and see if there's pushback.
