### ISSUE TITLE
Allow use in class

### ISSUE THREAD

**Issue by ntucker** [acdlite/redux-actions#133]
Say you want to make a method equal to createAction. Currently this doesn't work very well because this isn't accessible from the payloadCreator or metaCreator.

A simple change will make this work.

First change actionHandler from a lamba to a normal function so it takes on the this of the Class it is assigned to.

Second, bind this to payloadCreator and metaCreator before they are called.

**Comment by BerkeleyTrue** [comment]
Is this what you are trying to accomplish?

```jsx
class Foo {
  constructor() {
    this.handleAction = createAction(
      'HANDLE_ACTION',
      this.payloadCreator.bind(this),
      this.metaCreator.bind(this)
    );
  }
  payloadCreator() {
  }
  metaCreator() {
  }
}
```

**Comment by ntucker** [comment]
That's the intended result, yes. But of course, doing that defeats the purpose of createAction as it's purpose is to reduce code, so I want this to be able to do the same thing:

```javascript
class Foo {
  this.handleAction = createAction(
    'HANDLE_ACTION',
    function () {},
    function () {}
  )
}
```

**Comment by BerkeleyTrue** [comment]
Not saying this isn't a valid use case, but it seems like a bad smell to make action creators tied to every instance of a class. 

My approach to this kind of thing in the past is to do anything that requires context before calling the action creator with my data. 

Is there a reason this would not work or is undesirable? I can see the case of reducing the amount of code to write, but that seems a lot of burden to put on a third party library.

**Comment by ntucker** [comment]
I don't like polluting global namespaces - I prefer python over php. I don't see what's so intrinsically bad with namespacing that you have to ban others from using it.

The reason it currently does not work is because it is using lambdas which bind this at declaration time (in this case to undefined), rather than following the rules of methods. I don't see how moving from lambda to function declaration is a 'burden'. It literally does nothing for existing use cases.

**Comment by ntucker** [comment]
I'll create the PR, I have just been burned too many times to do a PR before I know it will be accepted.

**Comment by timche** [comment]
What's the purpose of creating actions in classes?

**Comment by yangmillstheory** [comment]
>What's the purpose of creating actions in classes?

I've never seen a Redux example where a class had action creation as a shared behavior. Is your class a React Component, local business object, or a helper module?

I'd encourage simplicity and using a functional programming style with Redux where possible.

**Comment by ntucker** [comment]
@timche To use classes. Well, that was obvious, so perhaps your real question is why is OOP even useful ever? This is probably a result of OOP functionality in javascript being traditionally extremely limited, and still lacking in many ways. However, even with JS's limitations that are cases where it is still very useful.

More on OOP here: https://www.quora.com/What-does-object-oriented-programming-do-better-than-functional-programming-and-why-is-it-the-most-popular-paradigm-when-everybody-seems-to-say-functional-programming-is-superior

I recommend reading the ENTIRETY of the above. Hope this clears things up :)

**Comment by yangmillstheory** [comment]
Er...

**Comment by ntucker** [comment]
And to be specific to my use case, I'm adding methods and factories to my immutable data structures. (I personally use Immutable.js - the thing Facebook made.)

**Comment by ntucker** [comment]
Arrow functions are not syntactic sugar - they change the binding behavior with regard to 'this'.

So when you write
```javascript
const actionCreator = (...args) => {
...
}
return actionCreator;
```

You're actually writing

```javascript
function actionCreator(...args) {
...
}.bind(this);
return actionCreator;
````

But nowhere in the code are you trying to attach this to anything specific - so you're adding extra lines of javascript to be executed just to destroy normal javascript behavior.

Changing this is quite trivial.

**Comment by BerkeleyTrue** [comment]
@ntucker Do you mind sharing your specific use case?

**Comment by ntucker** [comment]
Sure, I'll show you my immutable Class.

```javascript
export default function ModelRecord(defaultValues, name) {
  class Model extends Record.call(this, defaultValues, name) {
    static issueFind = createAction(
      FIND,
      undefined,     // use identity
      function() {
        return {
          Model: this,
        }
      }
    );
    ...
  }
}

Then something like for defining the model declaratively:

```javascript
export default class UserRecord extends ModelRecord({
  id: null,
  username: '',
  email: '',
  first_name: '',
  last_name: '',
}, 'UserRecord') {
  static urlRoot = `/api/user/`

  get fullName() {
    return [this.first_name, this.last_name].join(' ')
  }
}
```
