### ISSUE TITLE
redux-actions bundles lodash almost in its entirety 

### ISSUE THREAD

**Issue by lxe** [acdlite/redux-actions#134]
redux-actions.min.js is 32.4 kB, 82% of which is lodash:

<img width="1187" alt="screen shot 2016-09-20 at 4 21 26 pm" src="https://cloud.githubusercontent.com/assets/1486609/18692337/5432a226-7f4e-11e6-8cd0-554208a25124.png">

However, we only need the following things:

```
import camelCase from 'lodash/camelCase';
import identity from 'lodash/identity';
import includes from 'lodash/includes'
import isArray from 'lodash/isArray';
import isEmpty from 'lodash/isEmpty';
import isFunction from 'lodash/isFunction';
import isNil from 'lodash/isNil';
import isPlainObject from 'lodash/isPlainObject';
import isString from 'lodash/isString';
import isSymbol from 'lodash/isSymbol';
import reduce from 'lodash/reduce';
import toString from 'lodash/toString';
```

Looks like babel transforms these things just fine, only requiring individual files:

```
var _isString = require('lodash/isString');
```

I'm guessing maybe internally, lodash methods are just incredibly interconnected which causes such a hefty dependency weight.

**Comment by lxe** [comment]
lodash functions and their weights in minified bytes. 

```
22    isArray
23    identity
23    isFunction
23    isSymbol
80    isNil
189   isString
450   isPlainObject
687   isEmpty
1053  toString
1606  includes
5381  camelCase
17413 reduce
```

**Comment by timche** [comment]
Thanks for these extremely useful details!

**Comment by yangmillstheory** [comment]
@lxe What tool did you use to produce that visualization?
