### ISSUE TITLE
action.error cannot be set when Error object returned in payloadCreator

### ISSUE THREAD

**Issue by ypxing** [acdlite/redux-actions#138]
The behaviour has been changed by below commit

https://github.com/acdlite/redux-actions/commit/b9d5eb7daec5e29cb02c34dfb855c51183051f71

But we do depend on the original behaviour so that some basic validation can be done in our payloadCreator and set "error" for invalid cases.

Should we revert above commit back?

**Comment by yangmillstheory** [comment]
Can you do the validation outside the payload creator, passing in an `Error` object only when validation fails? 

Also, would https://github.com/acdlite/redux-actions/pull/136 fix this for you?

**Comment by ypxing** [comment]
Yes, I believe #136 should fix the issue since it will check the return value of payloadCreator.

I put basic validation in my action creator since I don't write another wrapper.
