### ISSUE TITLE
Actions without types throw an error rather than return the default state

### ISSUE THREAD

**Issue by JaKXz** [acdlite/redux-actions#140]
In my test setup code I have this line:

```js
test.beforeEach(t => {
  const initialState = reducer();
});
```

where

```js
const reducer = handleActions({ ... }, { /*initial state*/});
```

However, the first method throws an error because: 
![screen shot 2016-10-06 at 11 15 55 am](https://cloud.githubusercontent.com/assets/2642545/19158328/4b268bd8-8bb6-11e6-96b6-3cd65cbabdf2.png)

and in the transpiled source it looks like `action.type.toString()` is called unguardedly. Now, _maybe I'm misunderstanding how FSAs work_, but I think it makes sense for a reducer test to be able to check that the initial state is returned when the action type is missing. I can try to make a PR for this as well, if you think I'm correct about the expected behaviour.

If not, could you please fill me in on what I'm missing? Thanks!

**Comment by yangmillstheory** [comment]
A reducer returns the default state when the state given is undefined; the action must exist. This isn't FSA thing, just a Redux thing.

For tests around this, see 

- https://github.com/acdlite/redux-actions/blob/master/src/__tests__/handleAction-test.js#L170
- https://github.com/acdlite/redux-actions/blob/master/src/__tests__/handleAction-test.js#L15

For background material, see

- https://github.com/reactjs/redux/issues/514

**Comment by JaKXz** [comment]
Thanks @yangmillstheory - the background material helps.

Follow-up question:

I actually originally tried `reducer(undefined, {})` but that failed with the same error. Could that be a valid thing for `handleAction`?

**Comment by yangmillstheory** [comment]
See https://github.com/acdlite/redux-actions/pull/139#issuecomment-250376196 and the comment below it.

**Comment by JaKXz** [comment]
Sorry for the duplication/noise, and 🙏 for a great project! I thought I'd searched the issues properly but I guess not.

**Comment by yangmillstheory** [comment]
Out of curiosity, when do you encounter actions in your app that don't have a `type` property?

If you're using this library, `createActions` makes action creators that will always return actions with `type`.

**Comment by JaKXz** [comment]
Yeah at this point it's just 🚴🏚-ing about test setup code, I can't imagine a real example of having an undefined action or action type being dispatched. And I think I understand the argument that having the "robustness" to handle that is more bad than good.
