### ISSUE TITLE
React - Render an Action To show the details of that specific Work

### ISSUE THREAD

**Issue by hseleiro** [acdlite/redux-actions#146]
Dificult Question...Please Understand.

I'm trying to render an action when i click a button to show the details of that specific Work that i have on an array.The problem is that because the button is inside the the Map function, it repeats on all my Works, and i want a specific detail for each. Sorry if im not explaining very well.

This is my Work List Container -

    class ListaTrabalhos extends Component {

    renderList(){
    return this.props.trabalhos.map((trabalho) => {
        return (
            <li>
                <div className="row">
                    <div className="col-md-4">
                        <img key={trabalho.title} src={trabalho.img} />
                    </div>
                    <div className="col-md-8">
                        <h3>{trabalho.title}</h3>
                        <p>{trabalho.descricao}</p>
                        <button key={trabalho.title} onClick={() => this.props.selectTrabalho(trabalho)} type="button" className="btn btn-info">Detalhes</button>
                    </div>
                    <TrabalhoDetail />
                </div>
            </li>
        );
    })
    }

    render() {

    return (

    <ul className="list-group col-ms-4">
        {this.renderList()}
    </ul>

     );

     }
     }
This is my Work List Detail Container

    class TrabalhoDetail extends Component {
    render() {
    if (!this.props.trabalho) {
        return <div>Teste</div>;
    }

    return (
        <div>
            <h3>Detalhes:</h3>
            <div>{this.props.trabalho.title}</div>
            <div>{this.props.trabalho.tec}</div>
        </div>
        );
    }
    }

    function mapStateToProps(state){
    return {
    trabalho: state.activeTrabalho
    };
    }
I hope to be especific, if you need more info please tell-me , im new to this, and im trying to understand, already have made a lot of changes and its not working...Again, the objective is to show de Work details on a specific work that i click and not in all of them, The key is working so when i click a specific detail it gives-me the correct one, but keeps showing the others and i only want to see the one i click.

Thanks in advanced, sorry if its confuse.

    export function selectTrabalho(trabalho) {

    return {
    type: 'WORK_SELECTED',
    payload: trabalho
    };

    }

**Comment by yangmillstheory** [comment]
I'm not sure what the specific problem is.

Are you using `redux-actions`? If not, this might be better posted in https://github.com/gaearon/redux. 

How are you dispatching the action? I don't see any calls to `dispatch`.
