### ISSUE TITLE
Using thunk in map object for 'createActions' method.

### ISSUE THREAD

**Issue by jake-daniels** [acdlite/redux-actions#149]
I really like `createActions` method because it allows me to write pretty small definitions of action creators. Instead of 
```
export const changeSort = (newSort) => {
    return {
        type: Types.CHANGE_SORT,
        payload: {newSort: newSort}
    };
};
```
I simply create an item inside mapping object
```
export const Actions = createActions({
    [Types.CHANGE_SORT] : (newSort) => {
        return {newSort: newSort}
    },
});
```
Howewer, it seems that this method can't deal with thunks. I want to dispatch multiple actions in one action creator but still be able to define the action creator this way. Dumb example would look like this:
```
[Types.CHANGE_SORT] : (newSort) => {
    return (dispatch) => {
        dispatch({
            type: Types.DO_THING_BEFORE_SORT_CHANGE
        });
        dispatch({
            type: Types.CHANGE_SORT,
            payload: {newSort: newSort}
        });
    }
},
```
`redux-thunk` is unable to process this action because execution code (thunk) is wrapped in the **payload** of standard action instead of being the action itself.

**Is this the limitation of the method or am I missing something?**

**Comment by yangmillstheory** [comment]
I think this library is fairly unaware of thunks and middleware (which is good); it's only concern is providing utilities for creating Flux Standard Action (FSA) creators, and reducing said FSAs. 

So, `payloadCreator` is assumed to be a synchronous function that returns the `payload` value of an FSA.

I can give you some examples of how I integrate with `redux-thunk`.

```js
export function createClinicalReviewThunk(pioneerId, observationId) {
  return dispatch => arivaleXHR(
    '/api/clinical-review/reviews', {
      method: 'POST',
      body: JSON.stringify({
        observation_id: observationId,
        public_client_id: pioneerId,
        reviewer_role: appReviewerRole,
      }),
    },
  )
  .then(
    response => dispatch(createClinicalReview({
      response: normalize(deserialize(response.ClinicalReview), ClinicalReview),
    }))
  )
}

export function requestClinicalReviewsThunk(pioneerId) {
  return (dispatch, getState) => {
    const state = getState()
    if (
      selectors.getIsRequesting(state, pioneerId) ||
      selectors.getByPioneerId(state, pioneerId)
    ) {
      return Promise.resolve()
    }
    dispatch(requestClinicalReviews({ pioneerId }))
    return arivaleXHR(
      `/api/clinical-review/reviews?${querystring.stringify({ public_client_id: pioneerId })}`,
    )
    .then(
      response => dispatch(receiveClinicalReviews({
        response: normalize(response.ClinicalReviews.map(deserialize), arrayOf(ClinicalReview)),
        pioneerId,
      }))
    )
  }
}
```

I don't have any custom `payloadCreator`, but I could see pushing the calls to `normalize` and `deserialize` into one. This pattern has been working well for a 17K line Redux application.

**Comment by yangmillstheory** [comment]
I'm not sure how to make your intended code work without significantly warping core. Happy to continue the discussion regarding alternatives though.

**Comment by crobinson42** [comment]
@jake-daniels  I created a utility for this to use:

```
/**
 * A utility method to curry an action-creator that has a .toString() method to be used the same as
 * redux-actions actionCreator()
 * 
 * @param type {String}
 * @param thunk {Function} A redux-thunk, ie: (dispatch, getState) => { ... }
 * @returns {function(): *}
 */
export const createActionThunk = (type, thunk) => {
  const actionCreator = () => thunk

  actionCreator.toString = () => type

  return actionCreator
}
```

And in your project you use it like this:

```
const myAsyncAction = createActionThunk('myAsyncAction', (dispatch, getState) => { ... })
```

**Comment by jhenriquevissotto** [comment]
I have exactly the same problem today in 2020. Very sad to see that such a basic problem has been ignored.
