### ISSUE TITLE
Integrate redux-action-type-creator?

### ISSUE THREAD

**Issue by Darmody** [acdlite/redux-actions#150]
Hey,  I use `redux-actions` for a long time, and it is wonderful.

I just create a package for make action types definition in easy way:
https://github.com/Darmody/redux-action-types-creator

and thinking that maybe `redux-actions` can integrate `redux-action-types-creator`, because `action` and `action type` always been created together.

How do you think?

**Comment by yangmillstheory** [comment]
Is there anything preventing users from using the two libraries in conjunction?

I'd prefer to keep the core of this codebase focused on Flux Standard Action utilities for Redux. 

![image](https://cloud.githubusercontent.com/assets/2729079/19751321/2bda20ee-9bad-11e6-9773-39c44fa24550.png)


`redux-action-types-creator` doesn't seem to have anything to do with [Flux Standard Actions](https://github.com/acdlite/flux-standard-action/).

**Comment by Darmody** [comment]
@yangmillstheory Yeah, you are right, just asking.
Thank you anyway!
