### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by yangmillstheory** [acdlite/redux-actions#152]

**Comment by yangmillstheory** [comment]
Does anyone want to help out with this? Would be greatly appreciated, as the README is getting rather long and unruly. Perhaps we could use something like https://github.com/blog/2233-publish-your-project-documentation-with-github-pages?

**Comment by vinnymac** [comment]
@yangmillstheory I can take a swing at it. I would like to use gitbook if possible to stay consistent with `redux` and `redux-saga` documentation.

**Comment by yangmillstheory** [comment]
Thanks. Would you mind if I threw #172 and #204 in there as well? These are documentation-related issues. Completely on board with your proposed implementation.

**Comment by vinnymac** [comment]
@yangmillstheory sure, I will make a PR of all the goals and start on it today.
