### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by TimothyGu** [acdlite/redux-actions#153]
Hi,

I am in need of the change done in #136, which was merged last month and not yet published. If possible, could you please publish the changes?

Thanks.

**Comment by yangmillstheory** [comment]
https://github.com/acdlite/redux-actions/releases/tag/v0.13.0

https://github.com/acdlite/redux-actions/commit/4b6a9805f76063f6c8e93f864ad74279c55874a6

👌 ✌️ 🍻

**Comment by TimothyGu** [comment]
Thanks!
