### ISSUE TITLE
Crash for actions without action.type

### ISSUE THREAD

**Issue by baszalmstra** [acdlite/redux-actions#158]
redux-actions crashes when a middleware package (electron-redux-store) dispatches an action where type is null or undefined. It crashes since the latest release because of this code:

```
if (!includes(actionTypes, action.type.toString())) {
  return state;
}
```

`action.type` is `null` therefor toString cannot be called. 

I also filed this with redux-electron-store: https://github.com/samiskin/redux-electron-store/issues/34

**Comment by timche** [comment]
I'd say this is a `redux-electron-store` issue, because [Flux Standard Actions](https://github.com/acdlite/flux-standard-action) says, _"By convention, type is usually string constant or a Symbol."_.
