### ISSUE TITLE
fallthrough actions

### ISSUE THREAD

**Issue by smeijer** [acdlite/redux-actions#163]
In normal reducers we can use fallthrough to use the same reducing method for multiple action types. What's the easy way to do this in `redux-actions`?

```js
// normal reducer
switch (action.type) {
    case FETCH_ERROR:
    case CREATE_ERROR:
    case EDIT_ERROR:
    case DELETE_ERROR:
      return state
        .set('phase', ERROR)
        .set('error', String(action.payload.error));

  default:
    return state;
}
```

```js
// redux-actions
handleActions({
  [FETCH_ERROR]: (state, { payload }) => state
    .set('phase', ERROR)
    .set('error', String(payload.error));

  [CREATE_ERROR]: (state, { payload }) => state
    .set('phase', ERROR)
    .set('error', String(payload.error));

  [EDIT_ERROR]: (state, { payload }) => state
    .set('phase', ERROR)
    .set('error', String(payload.error));

  [DELETE_ERROR]: (state, { payload }) => state
    .set('phase', ERROR)
    .set('error', String(payload.error));
}, {});
```

Is this even possible?

I realize I can create a small helper function, and call this function 4 times, but still it doesn't look very nice:

```js
// redux-actions
const setError = (state, { payload }) => state
    .set('phase', ERROR)
    .set('error', String(payload.error));

handleActions({
  [FETCH_ERROR]: setError,
  [CREATE_ERROR]: setError,
  [EDIT_ERROR]: setError,
  [DELETE_ERROR]: setError,
}, {});
```

Anyone with suggestions to handle this in a clean way?

**Comment by xiaohanzhang** [comment]
have you checked `combineActions` ?

**Comment by yangmillstheory** [comment]
Yep, please see https://github.com/acdlite/redux-actions/#combineactionsactiontypes. Thanks @xiaohanzhang.

**Comment by smeijer** [comment]
Yes, I did see `combineActions`.  But even after rereading this section several times,  it's not directly obvious how to handle this case.

**Comment by yangmillstheory** [comment]
This is how we usually use it in code:

```js
handleActions({
  [
    combineActions(
      FETCH_ERROR,
      CREATE_ERROR,
      EDIT_ERROR,
      DELETE_ERROR
    )
  ]: (state, { payload }) => state
    .set('phase', ERROR)
    .set('error', String(payload.error));
}, {});
```

**Comment by smeijer** [comment]
That one is briljant. Can't believe it's not that obviously noted in the readme.

**Comment by yangmillstheory** [comment]
@smeijer Would you mind submitting a PR to improve the README?

**Comment by yangmillstheory** [comment]
Actually, this is taken care of in https://github.com/acdlite/redux-actions/pull/165/files.
