### ISSUE TITLE
v1.0.0 change too much

### ISSUE THREAD

**Issue by geminiyellow** [acdlite/redux-actions#167]
i use something like this,

```
handleActions({}, {})
```

but when i update to v1.0.0, it die.

and i use `redux-api-middleware`, create actions like 

```
{
  [CALL_API]: {
    type: [xxx]
  }
}
```

but when i update to v1.0.0, it die.

@acdlite i think you can find a more smoothly way to update, not like this.

**Comment by Lexicality** [comment]
What errors are thrown?

**Comment by timche** [comment]
Thanks for reporting.

I assume you are getting [this error](https://github.com/acdlite/redux-actions/blob/master/src/handleAction.js#L27-L30)?

**Comment by timche** [comment]
#168 has been opened to resolve this issue.

**Comment by timche** [comment]
We have published [v1.0.1](https://github.com/acdlite/redux-actions/releases/tag/v1.0.1).

**Comment by geminiyellow** [comment]
@timche thanks , and sorry i post 2 issues in 1

`export const shared = handleActions({}, {})`

```
Uncaught Error: Reducer "shared" returned undefined during initialization. If the state passed to the reducer is undefined, you must explicitly return the initial state. The initial state may not be undefined.
```

**Comment by timche** [comment]
What exactly trying to achieve with `export const shared = handleActions({}, {})`? The function signature is [`handleAction(type, reducer | reducerMap = Identity, defaultState)`](https://github.com/acdlite/redux-actions#handleactiontype-reducer--reducermap--identity-defaultstate). The default state is missing is [required in Redux](http://redux.js.org/docs/basics/Reducers.html).

**Comment by geminiyellow** [comment]
i just left the placeholder in the empty `reducer` file.
before v1.0.0, 

i can use
```
const shared = handleActions({}, {})

const reducers = {  shared, ui, ... };
const reducer = combineReducers(reducers);
```

create a empty state in store.
but now i cannot do this.

:trollface:

**Comment by timche** [comment]
As mentioned before, a default state is required in Redux, regardless of redux-actions. Also see: https://github.com/acdlite/redux-actions/issues/18

**Comment by yangmillstheory** [comment]
> Uncaught Error: Reducer "shared" returned undefined during initialization. If the state passed to the reducer is undefined, you must explicitly return the initial state. The initial state may not be undefined.


[is a`redux` error, not a `redux-actions` error.](https://github.com/reactjs/redux/blob/0139a9601dae810db533762c2bc4a745a37d4cf6/src/combineReducers.js#L65.)

**Comment by geminiyellow** [comment]
ok, i can use 

```
export const shared = state => state
```

i just want to tell you 0.13 can use 

```
const shared = handleActions({}, {})
```

but v1.0.0 cannot.
