### ISSUE TITLE
Usage with createStore preloadedState parameter?

### ISSUE THREAD

**Issue by nodegin** [acdlite/redux-actions#176]
Hi, I have the following code in my `app.js` reducer:
```js
const defaultState = {
  count: 1,
  type: null,
}

...

export default handleActions(reducerMap, defaultState)
```

And I am trying to preload the `type` state when creating the store:

```js
const preloadedState = {
  app: {
    type: "apple",
  },
}
const store = createStore(reducers, preloadedState, applyMiddleware(thunkMiddleware))
```

But I got the error that `count` state became `undefined`,
Seems by using `redux-actions` I was unable to check and assign state into defaultState

**Comment by yangmillstheory** [comment]
Can you share what your reducer looks like?

**Comment by nodegin** [comment]
@yangmillstheory 
```js
const reducerMap = {
  [actions.setCount]: (state, action) => ({
    ...state,
    count: action.payload,
  }),
}
```

**Comment by yangmillstheory** [comment]
What is `reducers` here?

```js
const store = createStore(reducers, preloadedState, applyMiddleware(thunkMiddleware))
```

**Comment by nodegin** [comment]
@yangmillstheory Oh sorry I missed that, here's the `reducers`

```
const reducer = handleActions(reducerMap, defaultState)
```

**Comment by yangmillstheory** [comment]
I think `preloadedState` [should have the same shape of your store state](https://github.com/reactjs/redux/blob/master/src/createStore.js#L25). The use case is 

> to hydrate the state from the server in universal apps, or to restore a previously serialized user session.

If you're not doing this, I'd recommend letting sub-reducers specify their default states.

***
In general, I think reducer composition would solve a lot of your problems. Try:

```js
const assert = require('assert')
const { combineReducers, createStore, applyMiddleware } = require('redux')
const thunkMiddleware = require('redux-thunk').default
const { handleActions } = require('redux-actions')

const count = handleActions({
  SET_COUNT(state, action) {
    return action.payload
  },
}, 1)

const type = handleActions({
  SET_TYPE(state, action) {
    return action.payload
  },
}, null)

const app = combineReducers({ type, count })

const store = createStore(
  combineReducers({ app }),
  applyMiddleware(thunkMiddleware)
)

assert.deepEqual(store.getState(), { app: { count: 1, type: null } })
store.dispatch({ type: 'SET_TYPE', payload: 'orange' })
assert.deepEqual(store.getState(), { app: { count: 1, type: 'orange' } })
store.dispatch({ type: 'SET_COUNT', payload: 100 })
assert.deepEqual(store.getState(), { app: { count: 100, type: 'orange' } })
```

Run this script and it should give you want you want.

**Comment by nodegin** [comment]
@yangmillstheory I see, thanks for helping!

**Comment by yangmillstheory** [comment]
![shipit](https://raw.githubusercontent.com/yangmillstheory/gifs/gh-pages/done/hand-wipe.gif)
