### ISSUE TITLE
handleAction should not response to falsy action type

### ISSUE THREAD

**Issue by watert** [acdlite/redux-actions#177]
Is this designed to be like this? Action passed in must be FSA or created by createAction?

```javascript
import { handleAction } from 'redux-actions'
describe('handle action with falsy type', () => {
  const increment = handleAction('INCREMENT', (state, action) => (state + 1), 0)
  it('should response to type INCREMENT', () => { // pass
    expect(increment(0, { type: 'INCREMENT' })).toBe(1);
  })
  it("should not response to type ''", () => { // fail
    expect(increment(0, { type: '' })).toBe(0);
  })
  it("should not response to type undefined", () => { // fail
    expect(increment(0, { type: undefined })).toBe(0);
  })
  it("should not response to type false", () => { // fail
    expect(increment(0, { type: false })).toBe(0);
  })
})
```

**Comment by yangmillstheory** [comment]
We made a change to enforce the action to be an FSA, but it broke a lot of users. So we reverted it in https://github.com/acdlite/redux-actions/commit/ef4acb7e06e3ea83ea6b1b58730d40087a7f069f#diff-b35552629f82c2c3dd19251a9cec2615.

Allowing strange `type` values seems to permissive, but it seems to be the right approach from a community standpoint for now.

**Comment by neverfox** [comment]
@yangmillstheory But this is a problem in its own right, isn't it? What's happening is that the "strange" action is being handled in the tests by the last listed handler (in this case, the only handler). I can't think of a good, practical reason for that behavior. The only time a handler should activate is on a match and those certainly aren't matches. It would seem more sensible to return current state unchanged, if throwing errors isn't desirable.
