### ISSUE TITLE
Merging defaultState with state

### ISSUE THREAD

**Issue by vansosnin** [acdlite/redux-actions#178]
I have a proposal to merge defaultState with state. Something like:

```javascript
{
   ...defaultState,
   ...state
}
```

For example, we have some _non-empty_ state and we want to add some fields which are not exist yet. Something like:

```javascript
const defaultState = {
    isCollapsed: true
};

export default handleActions({
    [types.TOGGLE_COLLAPSE]: state => ({
        ...state,
        isCollapsed: !state.isCollapsed
    })
}, defaultState);
```

It seems like the `defaultState` should be merged with our state. But now it is just being ignored because state is not empty.

**Comment by yangmillstheory** [comment]
What doesn't about this example work?

It would be great if you could share a code snippet in node.js with some [`assert`](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=node%20assert) statements. 

Looking forward to your response.

**Comment by vansosnin** [comment]
> What about this example doesn't work?

I expect that `state.isCollapsed` is _true_ but actually it is _undefined_ because my app state (not empty), there is no _isCollapsed_ and defaultState are not merged. I think it is good to have some defaultState for concrete reducer.

**Comment by yangmillstheory** [comment]
Are you specifying a `defaultState` in the root reducer?

**Comment by vansosnin** [comment]
For now yes, I have one _real_ defaultState in the root reducer. But it seems to be useful (and I propose it to be) to have a possibility to define defaultState for every reducer, isn't it? Especially since defaultState is _required_.

**Comment by vansosnin** [comment]
Ping. Are you aggree with my proposal? I can do a pull-request.

**Comment by yangmillstheory** [comment]
I'm not sure this is a good idea:

https://github.com/reactjs/redux/issues/1189#issuecomment-168025590

>This means when your reducers specify initial state and you also specify the initial state tree when creating the store, the state tree wins, just by the virtue of following the rules you outlined above. This lets you prefill the saved state for some reducers, and let others calculate their own initial state. This is a powerful pattern for universal apps that sometimes have initial state from the server and sometimes don't.

This is from the creator of Redux; I think it's saying that what you're proposing  goes against design.

**Comment by vansosnin** [comment]
Thank you for the answer.
