### ISSUE TITLE
Make defaultState non-optional

### ISSUE THREAD

**Issue by johanneslumpe** [acdlite/redux-actions#18]
Since we have to return a non-undefined state in redux, we should probably make the `defaultState` parameter for `handleActions` required. Thoughts?

**Comment by lukewestby** [comment]
I agree. It would be way more helpful for people to see a clear and explicit error up front than to try and figure out why Redux is complaining about their reducer all the way downstream.

**Comment by timche** [comment]
+1

I'll probably open a PR for this.

**Comment by yangmillstheory** [comment]
@timche are you still working on this, or can I self-assign?

**Comment by timche** [comment]
You can if you want.

**Comment by timche** [comment]
Fixed in #127.
