### ISSUE TITLE
handleAction always triggers if not FSA

### ISSUE THREAD

**Issue by inxilpro** [acdlite/redux-actions#185]
The code revert referenced in #177 results in `handleAction` always running the reducer if an action with no `type` is dispatched:

```js
if (type && !includes(actionTypes, type.toString())) {
  return state;
}

return (action.error === true ? throwReducer : nextReducer)(state, action);
```

It seems to me that it should be:

```js
if (!type || !includes(actionTypes, type.toString())) {
  return state;
}

return (action.error === true ? throwReducer : nextReducer)(state, action);
```

…so that the reducer simply returns the existing state if no `type` is provided in an action.

**Comment by inxilpro** [comment]
For anyone out there who's running into the same issue, a temporary fix is:

```js
const actionReducer = handleActions(/* ... */);
const reducer = (state = initialState, action) => {
	if (!action.type) {
		return state;
	}
	
	return actionReducer(state, action);
}
```

**Comment by ronaldheft** [comment]
Agreed on ignoring actions without a type.

I test all my reducers' default state by passing an empty action, and I've had to go through my tests and change them to use an invalid/unknown action instead.

**Comment by yangmillstheory** [comment]
Thanks: https://github.com/acdlite/redux-actions/releases/tag/v1.2.2 :beers:
