### ISSUE TITLE
Catch all handler?

### ISSUE THREAD

**Issue by babsonmatt** [acdlite/redux-actions#187]
I'm looking to create a catch all handler, similar to a default behavior in a switch statement, is there a way to do this? Apologies if this is obvious or I'm going about this wrong! 

Thanks!

**Comment by yangmillstheory** [comment]
I think you're going about this in an unconventional way.

>We return the previous state in the default case. It's important to return the previous state for any unknown action.

https://github.com/reactjs/redux/blob/master/docs/basics/Reducers.md

**Comment by babsonmatt** [comment]
@yangmillstheory thanks for the reply, just to clarify... how would you replicate something like this with redux-actions, or this is not a valid use case?

```const exercises = (state = {}, action) => {
  switch (action.type) {
  case 'CREATE_EXERCISE':
    return {
      ...state,
      [action.id]: {
        ...action.exercise
      }
    };
  case 'UPDATE_EXERCISE':
    return {
      ...state,
      [action.id]: {
        ...state[action.id],
        ...action.exercise
      }
    };
  default:
    if (action.entities && action.entities.exercises) {
      return merge({}, state, action.entities.exercises);
    }
    return state;
  }
}```

Thanks!
