### ISSUE TITLE
handleActions: Return current state if no actions match?

### ISSUE THREAD

**Issue by joncursi** [acdlite/redux-actions#188]
Here's a vanilla reducer that returns the current state when no actions match the switch:

```js
export const locationReducer = (state = locationInitialState, action) => {
  switch (action.type) {
    case SET_LOCATION_STATUS:
      return state.set(
        'status', action.payload
      );
    case SET_USER_LOCATION:
      return state.set(
        'location', action.payload
      );
    default: // this
      return state;
  }
};
```

From what I see in the docs, it is unclear if handleActions has this ability baked in or if it is missing (the ability to define this default case behavior). Thoughts?

**Comment by yangmillstheory** [comment]
https://github.com/acdlite/redux-actions/blob/master/src/handleAction.js#L27
