### ISSUE TITLE
Error in payload?

### ISSUE THREAD

**Issue by pronebird** [acdlite/redux-actions#189]
Hi,

In documentation you mention that if Error object is passed to action then it's returned back + error field is set to true. Could you elaborate on use case?

```js
const increment = createAction('INCREMENT');

const error = new TypeError('not a number');
expect(
increment(error) // WHY?
).to.deep.equal({
  type: 'INCREMENT',
  payload: error,
  error: true
});
```

**Comment by yangmillstheory** [comment]
The use case I'm thinking of is reducing the state according to the information present in the error (which can vary by error received for a given action). 

The example above is contrived, but you can imagine reducing state differently based on failed XHR calls (400 vs. 401 vs. 404 vs. 500). Thoughts?
