### ISSUE TITLE
Weird interaction with react-router-redux

### ISSUE THREAD

**Issue by pocesar** [acdlite/redux-actions#190]
I found that, when using `handleActions` and `combineReducers` alongside react-router-redux, the initial state coming out as `{ routing: [Object] }`

Upon investigating further, `handleActions` will only return the `initialState` if the current `state` is `undefined`, but react-router-redux is setting it to `{ routing: [Object] }`

react-router-redux triggers a dispatch with `{ type: '@@router/LOCATION_CHANGE' }` as soon it's loaded, and it happens before anything else, overwriting the original initialState that was set in `handleActions`, I'm having to manually set the initial state with a `initialState` action for this purpose.

It seems like a racing condition, but since react-router-redux always calls first, my initial state is always `{ routing: [Object] }` (which is the state added by react-router-redux).

**Comment by yangmillstheory** [comment]
Can you post a minimal code example illustrating your point?

**Comment by pocesar** [comment]
```ts
// reducer.ts
import { login } from './actions'

// login = createAction('LOGIN')

export const initialState: State = {
   /* ... */
  access: 'something'
}

const Reducer = handleActions<State>({
   [`${login}`]: (state, action) => {
       return { ...state }
   }
}, initialState)

export default combineReducers({
   ...Reducer, // or just Reducer, doesn't matter
  routing: routerReducer
})

// store.ts
import Reducer, { initialState } from './reducer'

const store = createStore(Reducer, initialState, applyMiddlewares(middlewares))

store.getState() // returns only `{ routing: [ Object ] }` no `{ access: 'something', routing: [ Object ] }`
```

**Comment by yangmillstheory** [comment]
https://github.com/reactjs/redux/blob/master/src/createStore.js#L28 

>If you use `combineReducers` to produce the root reducer function, this must be an object with the same shape as `combineReducers` keys.

Your `initialState` (`preloadedState` from the point of view of `createStore`) is missing the `routing` key. I'd start investigating from there.

By the way, whenever you populate `preloadedState` (as you're doing), you can generally expect it to override default reducer state (https://github.com/acdlite/redux-actions/issues/178#issuecomment-278153518). Is the initial state in the reducer necessary?

**Comment by pocesar** [comment]
after checking the source for redux-actions I noticed that the members of the parameter passed to `handleActions` aren't exposed. if it would have it set to `Object.defineProperty` with enumerable true, it would work as intended (with the spread operator), like this:

```ts
let obj = function() {} 
Object.defineProperty(obj, 'ok', { enumerable: true, value: () => {} })

let anotherObject = { ok2: () => {} }
{
...obj,
anotherObj
}
// becomes { ok: () => {}, ok2: () => {} }  
// in the case of combineReducers({ ...obj, routing: routerReducer }) would have the proper keys passed to the combineReducers
```

I can make a PR for it to work out of the box if it's interesting, otherwise I'll just hack my away

**Comment by yangmillstheory** [comment]
If you can accomplish what you can without too much code, I'd just advise doing that. In your case, I guess I'd have a subreducer for `access`, export that, and use the standard convention of 

```js
import access from './access'

const rootReducer = combineReducers({ access, router })
```

Not sure where you get `router` from, but presumably from `react-router-redux`.
