### ISSUE TITLE
action types as "export const"

### ISSUE THREAD

**Issue by Khorkhe** [acdlite/redux-actions#191]
I'm playing around with redux actions before deciding on integrating it with my project, and ran into the following: the createActions and handleActions functions take an object, (k, v) pairs.

previously, each action was defined as a const and exported. but the keys of the object in the two functions above cannot be variables.  so am i constrained to using strings if i want to use redux actions?

thanks

**Comment by yangmillstheory** [comment]
You can use ES6 computed object properties.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names

**Comment by Khorkhe** [comment]
@yangmillstheory very nice, thank you
