### ISSUE TITLE
Initial state conflicting with preloadedState argument in createStore

### ISSUE THREAD

**Issue by jfpalacios** [acdlite/redux-actions#193]
I am hydrating store with preloadedState argument and would like to listen to the @@redux/INIT event's state object that is being passed so I can merge defaults from handleAction's initial state with @@redux/INIT event's state. maybe initial state could also be a function and we can handle this there? Currently initial state is overwritten by preloaded state.

**Comment by yangmillstheory** [comment]
This is by design (Redux) See: https://github.com/acdlite/redux-actions/issues/178#issuecomment-278153518
