### ISSUE TITLE
When passing Error as payload, payload creator not called

### ISSUE THREAD

**Issue by mattwigway** [acdlite/redux-actions#194]
I have an action to handle putting an error message in the state for presentation to the user. I want to be able to call it with either a textual error message or a Javascript `Error` object; I want to normalize the arguments to the action creator before returning the action to be sent to the reducer. It seems like a payload creator within `createAction` would be the ideal way to do this. However, when you call an action creator created by `createAction` with an `Error` object, the payload creator is not called (note that the payload is not being modified by the trivial payload creator when the payload is an `Error`):

```
Matthews-MacBook-Pro:scenario-editor matthewc$ node
> const {createAction} = require('redux-actions')
undefined
> const action = createAction('action', (payload) => 12345)
undefined
> action('text')
{ type: 'action', payload: 12345 }
> action(new Error())
{ type: 'action',
  payload: 
   Error
       at repl:1:8
       at sigintHandlersWrap (vm.js:22:35)
       at sigintHandlersWrap (vm.js:96:12)
       at ContextifyScript.Script.runInThisContext (vm.js:21:12)
       at REPLServer.defaultEval (repl.js:346:29)
       at bound (domain.js:280:14)
       at REPLServer.runBound [as eval] (domain.js:293:12)
       at REPLServer.<anonymous> (repl.js:545:10)
       at emitOne (events.js:101:20)
       at REPLServer.emit (events.js:188:7),
  error: true }
> 
```

Is this intended behavior?

**Comment by yangmillstheory** [comment]
Pretty sure this is intended: https://github.com/acdlite/redux-actions/blob/master/src/createAction.js#L24.

Also see: https://github.com/acdlite/redux-actions/issues/82

**Comment by pho3nixf1re** [comment]
I just wasted half a day on this. Why are error's handled differently from any other data passed into the action creator? Isn't an Error object perfectly valid to be used to format a payload?

**Comment by sanbornhilland** [comment]
Just ended up here because of some really confusing debugging as well. I agree this is unexpected behaviour and could be more clearly documented. Is there a way to opt out of this behaviour? If not, would you be willing consider adding an option for that?
