### ISSUE TITLE
does redux-actions support prefixing types?

### ISSUE THREAD

**Issue by tugorez** [acdlite/redux-actions#195]
Hi everyone, I'm trying to figure out if something like this is currently possible with redux-actions:

```javascript
const prefix = 'some_random_prefix';
const type1 = 'SOME_RANDOM_TYPE_1';
const type2 = 'SOME_RANDOM_TYPE_2';
const type3 = 'SOME_RANDOM_TYPE_3';
const {
  someRandomType1,
  someRandomType2,
  someRandomType3,
} = createActions(
  { prefix },
  type1,
  type2,
  type3,
);
expect(someRandomType1().type).toEqual(`${prefix}/${type1}`);
expect(someRandomType2().type).toEqual(`${prefix}/${type2}`);
expect(someRandomType3().type).toEqual(`${prefix}/${type3}`);
```

and if not, might i know why? Thank you for your time :)

For example, [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/containers/HomePage/constants.js#9) endorses the fact of prefixing types to prevent unwanted behavior in reducers.

**Comment by yangmillstheory** [comment]
Take a look at https://github.com/acdlite/redux-actions/issues/159. I'll get this in tomorrow.

**Comment by tugorez** [comment]
@yangmillstheory  I did a [module](https://github.com/tugorez/redux-actions/blob/master/src/index.js) that wraps createAction ( I just did it for fun, It is really limited and just works in the case you use createActions with literal types). 
If there is something I could help you with, please tell me.

**Comment by yangmillstheory** [comment]
No problem. See this comment: https://github.com/acdlite/redux-actions/issues/159#issuecomment-282538877
