### ISSUE TITLE
ES6 Symbols break handleActions

### ISSUE THREAD

**Issue by billyjanitsch** [acdlite/redux-actions#20]
`handleActions` doesn't correctly match actions with types that are `Symbol`s, e.g.

```js
const TEST_ACTION = Symbol('TEST_ACTION')
const OTHER_TEST_ACTION = 'OTHER_TEST_ACTION'
const reducer = handleActions({
  [TEST_ACTION]: () => 'foo',
  [OTHER_TEST_ACTION]: () => 'bar',
}, 'baz')

let state = 'test'
state = reducer(state, {type: TEST_ACTION})
console.log(state) // test (unexpected)
state = reducer(state, {type: OTHER_TEST_ACTION})
console.log(state) // bar (fine)
```

`TEST_ACTION` is broken, `OTHER_TEST_ACTION` is fine.

**Comment by gaearon** [comment]
(Just FYI—while Redux supports symbols as action types, this is generally a bad idea. You won't be able to serialize your actions and replay them.)

**Comment by billyjanitsch** [comment]
^ (Great point. I only point this out because Symbols are starting to be used elsewhere leading to bugs like [this one](https://github.com/fcomb/redux-logger/issues/19), and if Redux is going to support them then its utilities probably should as well.)

**Comment by billyjanitsch** [comment]
Btw, looks like the problem is that Symbols aren't included in the array returned by `Object.keys` (by design -- see [this](http://blog.keithcirkel.co.uk/metaprogramming-in-es6-symbols/)). Should be a quick (if ugly) fix [here](https://github.com/acdlite/redux-actions/blob/master/src/handleActions.js#L5).

**Comment by acdlite** [comment]
Good catch. I think `Object.getOwnPropertyNames()` would work?

**Comment by gaearon** [comment]
@acdlite 

https://github.com/andreypopp/autobind-decorator/blob/954d825fcb585fa5747bba06505436cf56b3c287/src/index.js#L27-L38

**Comment by acdlite** [comment]
Yuck, okay, haha.

**Comment by acdlite** [comment]
Fixed in 0.8.0. Thanks!

**Comment by billyjanitsch** [comment]
Thanks for the quick fix! :)

**Comment by lukewestby** [comment]
Closing since this issue is fixed. Please reopen if anything else comes up. Thanks!
