### ISSUE TITLE
Actions must be plain objects. Use custom middleware for async actions.

### ISSUE THREAD

**Issue by 5argon** [acdlite/redux-actions#201]
From what I read, this should work

```
dispatch(createAction('INCREMENT'))
```

But it returns
```
Actions must be plain objects. Use custom middleware for async actions.
```

When I do 
```
console.log(createAction('INCREMENT'))
```

It returns
```
INCREMENT
```
on the console. I expect it to be a FSA (like `{ type:'INCREMENT', payload: ...`) but seems like it is just a string so it is not a plain object. What could be the problem here? (I have not use any middleware yet) And I have no idea how this simple operation could pass the `isFSA` in the test..

**Comment by yangmillstheory** [comment]
`createAction` creates an action creator. Check the README and #47.
