### ISSUE TITLE
Create store failed when use handleActions with empty reducerMap

### ISSUE THREAD

**Issue by JuoCode** [acdlite/redux-actions#202]
I have a `todosReducer`:
```
import { handleActions } from 'redux-actions';

const initState = {}

export default handleActions({

}, initState)
```

Error message:
```
Uncaught Error: Reducer "todos" returned undefined during initialization. If the state passed to the reducer is undefined, you must explicitly return the initial state. The initial state may not be undefined.
```

**Comment by yangmillstheory** [comment]
I think this is a usage issue. Why is your reducer map empty? It should at least declare an action.

**Comment by webholics** [comment]
I don't think this issue should've been closed.

handleActions should break if it gets an empty object as first parameter. But currently it breaks because in this case it does not return the initial state anymore. To me this is clearly a bug.

**Comment by yangmillstheory** [comment]
Good point. PR welcome.
