### ISSUE TITLE
Invalid regular expression:

### ISSUE THREAD

**Issue by sayll** [acdlite/redux-actions#209]
## deploy ： //  "NODE_ENV": "production"
Do not know why？
![image](https://cloud.githubusercontent.com/assets/18632641/25245420/e7ba0086-2636-11e7-815f-e594a64e9b0a.png)

**Comment by yangmillstheory** [comment]
Probably coming from https://github.com/acdlite/redux-actions/blob/master/src/camelCase.js. Can you start from that point?

**Comment by sayll** [comment]
thanks.
Missing  ！！  ` <meta charset="UTF-8">` ........
