### ISSUE TITLE
Can't pass object as the parameter into action creators created by `createActions` function.

### ISSUE THREAD

**Issue by huangc28** [acdlite/redux-actions#212]
I found issues when trying to pass object as parameter into action creator using following code: 

```
const {
  getIdeas,
  getIdeasSuccess,
  ...
} = createActions({
  GET_IDEAS: ({ status='', searchText='', limit='', offset='' }) => ({
    status,
    searchText,
    limit,
    offset,
  }) 
})
```

When I did so, I got following error:

```
TypeError: Cannot read property 'status' of undefined...
```

I want to be able to pass in object as parameters like I did when using ordinary action creator like so:

```
export const getIdeas = ({
  status='', 
  searchText='', 
  limit='', 
  offset=''
}) => ({
  status='', 
  searchText='', 
  limit='', 
  offset=''
})
```

so I can have extra flexibility manipulating the parameters pass into the action creator.

Is there any other way that I'm able to achieve such usage?

**Comment by yangmillstheory** [comment]
Can you show how `getIdeas` is being used and called?

**Comment by yangmillstheory** [comment]
Modifying https://github.com/acdlite/redux-actions/blob/45c3a78270eccb1e92f8a07564f66232cd7a734c/src/__tests__/createActions-test.js#L85 with

```js
it('should return a map of camel-cased action types to action creators', () => {
  const { actionOne, actionTwo } = createActions({
    ACTION_ONE: (key, value) => ({ [key]: value }),
    ACTION_TWO: ({ first, second }) => ([first, second])
  });

  expect(actionOne('value', 1)).to.deep.equal({
    type: 'ACTION_ONE',
    payload: { value: 1 }
  });
  expect(actionTwo({ first: 'value', second: 2 })).to.deep.equal({
    type: 'ACTION_TWO',
    payload: ['value', 2]
  });
});
```
passes, so I have to think it's an error in your code.

**Comment by huangc28** [comment]
@yangmillstheory, Thanks for you fast reply.

The following code is how I dispatch action creator in the component:

```
import { getIdeas } from '../../actions/ideas'

class Ideas extends Component {

  componentDidMount = () => {
    const {
      getIdeas,
      activeTab,
    } = this.props

    getIdeas({
      status: activeTab,
    })
  }
  // ... the rest of the component code...
}

export default connect(mapStateToProps, {
  getIdeas,
  ...
})(Ideas)
```

and this is my action creator

```
export const {
  getIdeas,
  ...
} = createActions({
  GET_IDEAS: ({
    status = '',
    searchText = '',
    offset = '',
    limit = '',
  }) => ({
    status,
    searchText,
    offset,
    limit,
  })
})
```

Im expecting to get an action creator with a format like:

```
export const getIdeas = ({
    status = '',
    searchText = '',
    offset = '',
    limit = '',
  }) => ({
  type: GET_IDEAS,
  payload: {
    status,
    searchText,
    offset,
    limit',
  }
})
```
but am still getting error stated in the first post.

**Comment by yangmillstheory** [comment]
This should work based on https://github.com/acdlite/redux-actions/issues/212#issuecomment-301340967, can you post the full stack trace? Where is the error (line of code) being thrown? What happens you set a breakpoint in the browser debugger?

**Comment by yangmillstheory** [comment]
Closing due to lack of response.
