### ISSUE TITLE
Allow nested reducers in handleActions

### ISSUE THREAD

**Issue by roboslone** [acdlite/redux-actions#215]
It was really surprising for me that `createActions` can handle nested objects while `handleActions` can't. I think this example looks very natural and readable:
```js
const defaultState = {
    query: undefined
}

export const actionCreators = createActions({
    SEARCH: {
        SET_QUERY: text => text,
    }
})

export const reducer = handleActions({
    SEARCH: {
        SET_QUERY: (state = defaultState, action = {}) => {
            return {...state, query: action.payload}
        },
    },
}, defaultState)
```

But it doesn't work. Instead `reducer` must be:
```js
export const reducer = handleActions({
    'SEARCH/SET_QUERY': (state = defaultState, action = {}) => {
        console.log('reducer.search.setQuery <-', state, ',', action)
        return {...state, query: action.payload}
    },
}, defaultState)
```

My IDE autocompletes with first example and doesn't with the second.

Would it be possible to allow such nested structures in `handleActions`?

**Comment by roboslone** [comment]
ping

**Comment by yangmillstheory** [comment]
That sounds reasonable; feel free to take a shot at a pull request. I would ask that you preserve backwards-compatibility as well. I believe the key algorithm is already in this library. What do you think of taking up this work yourself?

**Comment by roboslone** [comment]
Not sure if I'm up to the task, I have little experience with JS =/

**Comment by roboslone** [comment]
@zcei @yangmillstheory Thanks!
