### ISSUE TITLE
’ (apostrophe) in var "wordPattern"  Issue 

### ISSUE THREAD

**Issue by homs44** [acdlite/redux-actions#217]
Hi.  I am developing  web application with this library.  and I use AWS S3 for website hosting 

My app occur Error in IE. the error is related with regex

after new minutes. I realized that S3 change ’  to â€™ in var "wordPattern"

var wordPattern = /[A-Z\xc0-\xd6\xd8-\xde]?[a-z\xdf-\xf6\xf8-\xff]+(?:['’](?:d|ll|m|re|s|t|ve))

below is in S3
var wordPattern = /[A-Z\xc0-\xd6\xd8-\xde]?[a-z\xdf-\xf6\xf8-\xff]+(?:['â€™](?:d|ll|m|re|s|t|ve))

**Comment by yangmillstheory** [comment]
Can you reproduce this by uploading a small text file to S3? Are you sure whatever build tool you're using isn't responsible?

**Comment by homs44** [comment]
yeah. I uploaded JS file and other text files with same content
The JS file is only changed.

**Comment by yangmillstheory** [comment]
Take a look at https://stackoverflow.com/a/34947592/2419669; this is an encoding issue.

**Comment by homs44** [comment]
Thank you!
