### ISSUE TITLE
How can I use auto-complete for action creator's parameters?

### ISSUE THREAD

**Issue by ohtangza** [acdlite/redux-actions#219]
When we manually create the action creator, most of the editors (like VSC) automatically displays the type and name of the parameter variable.

However, if we use `redux-actions`, the name of parameters are all unified into `payload` which is difficult to interpret during development.

- Is there any way I can add JSDoc comment on created actions creators?
- Is there any way I can use TypeScript or @Flow for the type checking for parameters?

**Comment by yangmillstheory** [comment]
Not sure, I don't use really use either. Let me know what you find out.

**Comment by ohtangza** [comment]
@yangmillstheory Our team decided to use only handleActions() for now. Removed all the createAction() because we cannot take advantage of all the linter function.
