### ISSUE TITLE
createActions is converting constant names to camel case

### ISSUE THREAD

**Issue by JuliusKoronci** [acdlite/redux-actions#224]
I am not sure if this is intended but it cause as quiet a bug which was hard to find. We used the reducer name stored in a constant to create actions..and later on in the app we built upon the constant..one of my colleagues changed the constant from partnerCrud to partnerCRUD..since we were expecting the actions created to be partnerCRUDAction we were created a quiet big bug in the application..which took really long to debug

I would suggest that the createdActions will keep whatever name was passed to it

**Comment by yangmillstheory** [comment]
This is intended, based on the Redux naming conventions for actions. See https://decembersoft.com/posts/a-simple-naming-convention-for-action-creators-in-redux-js/.
