### ISSUE TITLE
Redux middleware with Redux actions

### ISSUE THREAD

**Issue by abraztsov** [acdlite/redux-actions#229]
Why `react-actions` return object with value and payload Instead of returning just payload ?

```
const asyncCall = createAction(CALL, async () => {
  const response = await api.getSmth();
  return response;
});

const response = await props.asyncCall(); 
console.log(response) // { payload: MYDATA, type: CALL }
```

expected just `MYDATA` without returning whole object with `type`

**Comment by timche** [comment]
It's a [Flux Standard Action](https://github.com/acdlite/flux-standard-action). This library is based on that.
