### ISSUE TITLE
Wrapping reducer in handleAction throws undefined state

### ISSUE THREAD

**Issue by Bartvds** [acdlite/redux-actions#23]
If I wrap a reducer in `handleAction` I get this error:

> "Reducer "selectedReddit" returned undefined during initialization. If the state passed to the reducer is undefined, you must explicitly return the initial state. The initial state may not be undefined."

If I debug I see redux tries to get a initial state by calling the wrapped reducer with undefined state and a specific system action type. Because the type does not match the wrapped one the inner reducer never runs and no state default is created.

If I use `handleActions` (m) with default state it works fine. Same function with default state in arguments and classic action-type check is also fine.

Anyway,is `handleAction` usable like this? Readme doesn't really specifiy use case.

**Comment by iest** [comment]
Got this error too. Using `handleActions` instead and passing a default state worked for me as well.

**Comment by yoavniran** [comment]
yup, running into this as well. Seems like handleAction is broken with initial state being undefined...

**Comment by drhayes** [comment]
Happening for me too. Same workaround.

I'm getting it because I'm passing the resultant reducer to `combineReducers` from redux. It aggressively "ensures reducer sanity" by passing undefined initially. Third arg, maybe?

**Comment by tony-kerz** [comment]
i get this:
```
Uncaught Error: Reducer "loginReducer" returned undefined during initialization. If the state passed to the reducer is undefined, you must explicitly return the initial state. The initial state may not be undefined.
```
from this:
```
export const loginReducer = handleAction(
  actions.LOGIN,
  (state={}, action) => {
    return {
      ...state,
      session: {
        active: true
      }
    }
  }
)
```
this is with redux-actions `0.8.0` (alongside of redux-promise `0.6.0-alpha` if it matters)

i'm assuming this is the same issue...

**Comment by talarari** [comment]
Getting the same error

**Comment by startupthekid** [comment]
I'm also running into this error. Will it ever be addressed? It was first reported back in August and now it's 2016.

**Comment by popc0rn** [comment]
Same problem here when I define reducers with `handleAction` and then try to combine them with `combineReducers` from redux. They go through internal `combineReducers` sanity check that calls them without passing an state or action an that crashes the function

**Comment by saiichihashimoto** [comment]
Same

**Comment by danny-andrews** [comment]
+1

**Comment by emiloberg** [comment]
For others finding their way in here:

Note that `handleActions` (plural) works but want the default state as the second **argument** to `handleActions`. As [can be seen in the readme](https://github.com/acdlite/redux-actions#handleactionsreducermap-defaultstate) or in [this example](https://github.com/acdlite/redux-actions/issues/54#issue-125032461)

**Comment by lsunsi** [comment]
Same problem. So handleAction is practically unusable, right?

**Comment by timche** [comment]
I don't know since when Redux is doing this sanity check, but without an initial state, `handleAction` is definitely unusable.

Nevertheless, #55 adds support for that.

**Comment by evenfrost** [comment]
Looking forward to this as well, going through the Redux tutorial and `handleAction` bundled with `combineReducers` throws the error.

**Comment by yangmillstheory** [comment]
@timche isn't this closed with 0.10.0?

**Comment by timche** [comment]
Thanks @yangmillstheory 👍

**Comment by vtvz** [comment]
Solution:

```javasctipt
const loadStateReducer = handleAction(loadState, (state, {payload}) => {
    return payload;
}, {}); // <-- default state
```
[The reason why this happens](https://github.com/acdlite/redux-actions/blob/master/src/handleAction.js#L14)

**Comment by KalidassM01** [comment]
You have to add **default: return state;** at the bottom of all cases of your switch function. Hope this work. Good luck
