### ISSUE TITLE
No default return state for handle-action(s) of redux action

### ISSUE THREAD

**Issue by v07h4nhd47** [acdlite/redux-actions#235]
Normally, in a reducer function,  we can change the default state of course. For example:
`export default function reducer(action,state){`
  `switch(action.type){`
  `  case ' ... ': return ..; break;`
   ` ...`
   ` default: return custom(state);`
 ` }`
`}`
how can we make this possible when implementing handle-action(s)?

**Comment by timche** [comment]
This would be possible, yes. 

Redux has been designed to return the previous state for any unknown action, so is redux-actions. It is not recommended to change the previous state in any way to avoid unintended side-effects.

> [2. We return the previous state in the default case. It's important to return the previous state for any unknown action.](http://redux.js.org/docs/basics/Reducers.html)
