### ISSUE TITLE
How to set error to true?

### ISSUE THREAD

**Issue by rightaway** [acdlite/redux-actions#24]
When creating an FSA-compliant action that represents an error (`error` property set to `true`), how can I do that? Sorry if it's an obvious answer.

**Comment by ngokevin** [comment]
Waiting on https://github.com/acdlite/redux-actions/pull/16

**Comment by lukewestby** [comment]
@rightaway #16 was merged, so I'm going to close this for now. You can try out the new functionality by running your code against the master branch, and keep an eye out for the next release. We're tracking this in some other issues as well, so if you find you still can't get things working as expected, leave another comment here and we'll organize all the outstanding concerns in a single issue.

Thanks!
