### ISSUE TITLE
how to import it?

### ISSUE THREAD

**Issue by capaj** [acdlite/redux-actions#26]
`import createAction from 'redux-actions';`

or

`import { createAction } from 'redux-actions';`

??
Why is this missing in the readme?

**Comment by johanneslumpe** [comment]
A quick look at the source code which you can find (here)[https://github.com/acdlite/redux-actions/blob/master/src/index.js] will tell you that you should do

`import { createAction }  from 'redux-actions'`

**Comment by lukewestby** [comment]
@johanneslumpe do you think this should be incorporated into the README, maybe right under the `npm install` instructions?

**Comment by timche** [comment]
Closing this, because the README has been adjusted since this issue.
