### ISSUE TITLE
createActions

### ISSUE THREAD

**Issue by appsforartists** [acdlite/redux-actions#39]
Just as there's a `handleActions`, perhaps there should be a `createActions` as sugar for creating multiple actions?

```javascript
createActions(
  {
    [type1]:  payload1Creator,

    [type2]:  {
                "payload":  payload2Creator,
                "meta":     meta2Creator,
              }
  }
);
```

This seems a bit nicer (and less redundant) than

```javascript
{
  [type1]: createAction(type1, payload1Creator),
  [type2]: createAction(type2, payload2Creator, meta2Creator),
}
```

**Comment by msafi** [comment]
Came here to ask for this.

In my case I did

```
mapValues(myActionTypes, (actionType) => createAction(actionType));
```

**Comment by appsforartists** [comment]
@msafi https://github.com/pauldijou/redux-act looks pretty sweet too.

**Comment by timche** [comment]
Since there are no more opinions on that, I'll close it for now. Re-open if necessary.
