### ISSUE TITLE
handleAction/handleActions: should set a default `throw` function

### ISSUE THREAD

**Issue by ustccjw** [acdlite/redux-actions#4]
For async action, rejected promise then wrap to FSA: `{error: true, payload: [Error Object]}`, always we should `{return state}`.

FSA says `if the status is error, the payload SHOULD be an error object`, i can't understand why handleAction/handleActions: `If a single reducer is passed, it is used to handle both normal actions and failed actions`.

**Comment by acdlite** [comment]
Yeah you're right, we should probably treat a single reducer the same as a `next()` handler.
