### ISSUE TITLE
Is there a way to get state in createAction?

### ISSUE THREAD

**Issue by ipselon** [acdlite/redux-actions#41]
Is there a way to get state in createAction?
Is it wrong approach if I need to get data from state inside action creator?

**Comment by lukewestby** [comment]
Hi @ipselon, thanks for your question.

This is not the recommended approach for simple actions created through a result of `createAction()`. If you need to compose an action's payload from other state one option is to do so in your component before you call your action creator. If your action is sufficiently complex that you need to encapsulate the logic in the action creator itself I would recommend using `redux-thunk` https://github.com/gaearon/redux-thunk , which will allow you to access state via a `getState()` function.

**Comment by ipselon** [comment]
Hi @lukewestby, thanks for answering.

I know about redux-thunk, but I prefer to use sequenced actions with redux-promise. Actually, I agree with you to not to obtain the whole state in action creator and to pass some data from component to action. There is only one isue with this, if component has to pass data from a part of state tree it has to include that particular part through the redux mapping. Consequently, that component will receive changes from redux provider (or whatever there is). And in this situation we need to use selectors to prevent unnecessary updating.

**Comment by lukewestby** [comment]
Is it possible to use `redux-promise` in conjunction with `redux-thunk`? You could create a thunk action creator to wrap your promise action creator which composes the payload from state before dispatching a promise.

**Comment by ipselon** [comment]
Will check, I thought about this already but didn't try. Thanks.

**Comment by lukewestby** [comment]
@ipselon I'm going to close this for now, but just add another comment if that strategy doesn't work out and we can reopen or start a discussion somewhere else. Thanks!

**Comment by crobinson42** [comment]
@ipselon, if you're using `redux-thunk` you could add and use this utility method:

```
/**
 * A utility method to curry an action-creator that has a .toString() method to be used the same as
 * redux-actions actionCreator()
 * 
 * @param type {String}
 * @param thunk {Function} A redux-thunk, ie: (dispatch, getState) => { ... }
 * @returns {function(): *}
 */
export const createActionThunk = (type, thunk) => {
  const actionCreator = () => thunk

  actionCreator.toString = () => type

  return actionCreator
}
```
