### ISSUE TITLE
npm package redux-actions contains old code.

### ISSUE THREAD

**Issue by w-site** [acdlite/redux-actions#45]
npm package redux-actions contains old code, for ex. it hasn't "Handle FSA errors where the payload is an Error object. Set error." in createAction.js could you please update npm package. Thanks.

**Comment by wginolas** [comment]
+1

The commit "Fix issue when rejecting a promise for a single reducer" would also be very helpful for me.

**Comment by adros** [comment]
+1

**Comment by michaeljones** [comment]
+1, just spent some time confused by why I wasn't getting `action.error = true`. Love a release if it is stable code.

**Comment by uhercik** [comment]
+1

**Comment by lukewestby** [comment]
Ping @acdlite would it be possible to do an npm publish soon?

**Comment by acdlite** [comment]
v0.9.0 published :)
