### ISSUE TITLE
.babelrc cause error on babel6

### ISSUE THREAD

**Issue by tdzl2003** [acdlite/redux-actions#49]
There is a .babelrc published on npm, which is configured for babel5. It will cause error on babel 6, like react-native >=0.16.0

Is it ok to add it into '.npmignore' and does not publish it on npm?

**Comment by alvaromb** [comment]
Same here!

**Comment by despairblue** [comment]
Here is a [workaround](https://github.com/michaelcontento/redux-storage/issues/65#issuecomment-167160035).

**Comment by tdzl2003** [comment]
This workaround is only for *nix system and it will broke some module that exported with ES6.
I have my own workaround on my project, but it will be better to not publish it to npm

**Comment by despairblue** [comment]
> I have my own workaround on my project, but it will be better to not publish it to npm

Though sharing it in any other way might still help other people who end up here while searching for a solution.

**Comment by anderson916** [comment]
+1

**Comment by adrienbrault** [comment]
:(

**Comment by marcelklehr** [comment]
Same here, please add .babelrc to .npmignore or else fix it.

**Comment by acdlite** [comment]
Oops! Fixed in 0.9.1

**Comment by marcelklehr** [comment]
thank you! :)

**Comment by alvaromb** [comment]
The fix doesn't work for me, I think it's due to this other issue https://github.com/acdlite/flux-standard-action/issues/24

**Comment by tantou** [comment]
The fix doesn't work for me too, cause by the flux-standard-action
