### ISSUE TITLE
How to use combineReducers to add multiple reducers that use the same action type?

### ISSUE THREAD

**Issue by pixeldrew** [acdlite/redux-actions#54]
I'm using combineReducers and i'm wondering how I can use handleActions to have two different store keys be updated by the one action type. My requirement is that the one action type be used to update different keys inside the store, for example I have a transactions array which must add a new transaction then I must update the balance of the account the transaction relates to.

This doesn't seem to work, or am I doing this wrong?
```js
import { combineReducers } from 'redux';
import { handleActions } from 'redux-actions';

const ADD_TRANSACTION = 'ADD_TRANSACTION';
let defaultTransactionsState = [];
let defaultAccountsState = [];

// add transaction to transactions state
let transactions = handleActions({
  [ADD_TRANSACTION]: (state, action) => ([action.payload, state...])
}, defaultTransactionsState);

let accounts = handleActions({
  [ADD_TRANSACTION]: (state, action) => {
    // update the balance of account based on transaction being added
    let payload = action.payload;
    let accountToEdit = state.find((account) =>  account.id === payload.accountId);
    let newBalance = accountToEdit.balance + (payload.inAmount - payload.outAmount);

    return state.map(account =>
      account.id === accountToEdit.id
        ? {...account, balance: newBalance}
        : account
    );
  }
}, defaultAccountsState);

combineReducers({
  transactions,
  accounts
});
```

**Comment by acdlite** [comment]
The overall approach looks fine — any reducer in `combinedReducers()` is able to respond to any action type.

I did notice some bugs with your code, though. In your second reducer, `accounts` is the name of the reducer, not the current accounts state. So

```diff
- let accountToEdit = accounts.find((account) =>  account.id === payload.accountId);
+ let accountToEdit = state.find((account) =>  account.id === payload.accountId);
```

and

```diff
- return accounts.map(account =>
+ return state.map(account =>
```

Maybe that fixes the problem you're having? If not, please give some more details and I'll see if I can help.

**Comment by pixeldrew** [comment]
ah yeah, that's just for the example I simplified. Perhaps I have other errors in my code I need to take a look at.

**Comment by pixeldrew** [comment]
Doh... yep I had a constant exported and it wasn't picking it up in the other model

**Comment by pixeldrew** [comment]
Side note, would love to get a CDN/UMD version of this library to throw up jsfiddles or jsbin's
