### ISSUE TITLE
flux-standard-action dependency not necessary

### ISSUE THREAD

**Issue by someok** [acdlite/redux-actions#60]
handleAction use **flux-standard-action** method **isError**

> import { isError } from 'flux-standard-action';

the method is simple, but it will import some lodash method when compile by webpack.

```
function isError(action) {
  return action.error === true;
}
```

I suggest remove the flux dep for descrease the compilse file size.

**Comment by nico-schneider** [comment]
I think the purpose here is to have the actual logic that decides whether an action is an error in the `flux-standard-action` repository. So if anything ever changes in the flux action standard, say, `error: true` moves inside the `meta` key, these checks remain unaffected. 

"Go ahead and save yourselves some technical debt" I believe is in one of @gaearon's readmes.

**Comment by albertogasparin** [comment]
I'm also supporting the removal of the `flux-standard-action`. It adds several KB of dependencies for no reason. Actually, in `createAction.js` you are already setting the error prop regardless of the FSA behaviour:

``` js
if (args.length === 1 && args[0] instanceof Error) {
  action.error = true;
}
```

The result is that the lib will be "broken" whenever FSA `isError` method will change. I think a better approach would be adding some FSA checks in the unit tests, so the build will automatically fail on conventions changes.

**Comment by acdlite** [comment]
Sounds good to me if you want to submit a PR

**Comment by albertogasparin** [comment]
PR done #76
Feel free to review and merge (but you should merge #62 first in order to fix master)
