### ISSUE TITLE
[Question] How do I dispatch multiple actions in one action?

### ISSUE THREAD

**Issue by Industrial** [acdlite/redux-actions#61]
Hi.

Say I have one action `initialize`, for this as for many actions I am dispatching an `action:start`, `action:success` and `action:failure`. Most of these have counterparts in the reducers where they update properties like `isFetching`, `isSaving`, etc.

If I use `redux-actions` instead of `redux-thunk` then how do I let my reducers know the correct state at the correct time? If I can only dispatch one event at the end of one action then I can't dispatch multiple actions/events from one action ..

**Comment by addnab** [comment]
`redux-thunk` is a middleware unlike `redux-actions` which is a utility library for creating and handling actions. So you can still continue to use `redux-thunk` to dispatch multiple actions and use `redux-actions` API to `handleActions` like:

`reducers.js`
```
const reducer = handleActions({
  FETCH_REQUEST: (state, action) => ({
    ...state,
    fetchError: false,
    isFetching: true,
    displayText: "Fetching..."
  },

  FETCH_SUCCESS: (state, action) => ({
    ...state,
    fetchError: false,
    isFetching: false,
    displayText: action.payload
  }),

  FETCH_FAILURE: (state, action) => ({
    ...state,
    fetchError: true,
    isFetching: false,
    displayText: action.payload 
  })
});
```

`action.js`
```
const fetchRequest = createAction('FETCH_REQUEST')
const fetchSuccess = createAction('FETCH_SUCCESS')
const fetchFailure = createAction('FETCH_FAILURE)
const fetch = (url) => {
    return async (dispatch, getState) => {
        try {
            dispatch(fetchRequest())
            const response= await _fetch(url)
            if(result.statusCode !== 200)
                throw new Error()
            const result = await response.json()
            dispatch(fetchSuccess(result))
        }
        catch(error) {
            dispatch(fetchError(error))
        }
    }
}
```

**Comment by Industrial** [comment]
Okay,

so then in my components where do I pass dispatch? or is the `redux-thunk` library still doing that?

```js
function mapDispatchToProps(dispatch) {
  return {
    fetch: (url) => dispatch(actions.fetch(url))
  };
}
```

**Comment by addnab** [comment]
@Industrial Yes, you don't have to pass `dispatch` while dispatching the action. If the action returns a function of the form `foo(dispatch, getState)`, then `redux-thunk` middleware should take care of calling that function by passing `dispatch` and `getState` as arguments to that function.

**Comment by timche** [comment]
Seems like the question has been answered.

**Comment by moersing** [comment]
@addnab  Thank you , This is good solution.
