### ISSUE TITLE
createAction - need a means to set action.meta if payload is an error

### ISSUE THREAD

**Issue by ericlau-solid** [acdlite/redux-actions#67]
> export const FAILED_REQUEST_ORDER = `${GET_FUNCTIONALITY}_FAILED`;
> export const failedOrder = createAction(FAILED_REQUEST_ORDER);
> 
> // in calling code
> 
> // ...
> .catch(error) {
>   const errorMeta = {
>         'endpoint': endpoint,
>         'options': options
>       };
>   dispatch(failureAction(error, errorMeta));
> }

I would like to dispatch an error object as a payload, but also have meta data information. I can hack around it, but I think it makes sense for createAction to provide a means to set meta separately from payload. This is important for error handling. Thanks for your time.
-- currently I can't perform the code above, even though I think it should be able to do so) -- a hack exists where I do this:

>     .catch((error) => {
>       const errorMeta = {
>         'endpoint': endpoint,
>         'options': options
>       };
>       let failureActionObject = failureAction(error);
>       failureActionObject.meta = errorMeta;
>       dispatch(failureActionObject);
>     });

**Comment by timche** [comment]
Could be fixed with #66. Let's move this discussion there.
