### ISSUE TITLE
payloadCreator is executed even when an Error is passed

### ISSUE THREAD

**Issue by kilianc** [acdlite/redux-actions#82]
```js
const favoriteEnd = createAction(types.FAVORITE_END, (id) => ({ id }))
favoriteEnd(15) // payload.id === 15
favoriteEnd(new Error('foo')) // payload.id === error
```

while I'd expect 

```js
favoriteEnd(new Error('foo')) // payload === error
```

Am I missing something ?

**Comment by timche** [comment]
Nope, you're not missing something. Have a look what's happening in [`createAction`](https://github.com/acdlite/redux-actions/blob/master/src/createAction.js#L16-L19).

`payload` won't be changed, but I'd also expect that behaviour that `payload` doesn't use the function.

I think, we need to fix this.

**Comment by kilianc** [comment]
I hope @casparrolfe PR lands soon, this is so annoying

**Comment by yangmillstheory** [comment]
It looks like this was closed by https://github.com/acdlite/redux-actions/commit/b9d5eb7daec5e29cb02c34dfb855c51183051f71?
