### ISSUE TITLE
Possible feature: have handleAction() transfer payload to state when reducer is undefined

### ISSUE THREAD

**Issue by jcheroske** [acdlite/redux-actions#89]
This could be a really bad idea, but I thought I'd run it by you. I often find that I'm just wanting to write a quick reducer that just moves the action's payload to the state. Being able to just type:
```
const reducer = handleAction(ACTION_TYPE, initialState);
```
instead of
```
const reducer = handleAction(ACTION_TYPE, (_, {payload}) => payload, initialState);
```
would be really nice. Just a thought.

**Comment by timche** [comment]
I'll leave this issue open for few opinions on that idea.

**Comment by Lucretiel** [comment]
+1

This would probably pair well as a further specialization of my own idea to allow reducers with the signature `(state, payload) => state` instead of `(state, action)` => state`

**Comment by timche** [comment]
@yangmillstheory What do you think about this?

**Comment by yangmillstheory** [comment]
I think it belongs in userland. Just define a reusable helper in your code:

```js
const noopFSAReducer = (state, { payload }) => payload 

export default noopFSAReducer
```

**Comment by timche** [comment]
Closing it then for now, feel free to comment in here to re-open this feature request.
