### ISSUE TITLE
Identity function, hidden gotchas and 300-400ms to dispatch your actions

### ISSUE THREAD

**Issue by Restuta** [acdlite/redux-actions#90]
Just want to discuss this, since was confused by default actionCreator factory behaviour. As per docs if I define my action crator like that:

`export const toggleBaseline = makeActionCreator('Dbg.TOGGLE_BASELINE')`

identity function will be used for payload. I assumed that it's fine to create Action Creators that don't have a payload in this manner and it was wrong assumption. Read below why.

After creating it I passed it to my component like that:

```
export default connect(state => state.debug, {
  toggleBaseline,
})(DebugGrid)
```

Then inside `DebugGrid` component I just hooked it to `onClick` handler:

`<input type="checkbox" onChange={props.toggleBaseline}`

All seemed fine, do you see a problem at this point? I didn't see any =) And if you don't see it also then we have a problem and need to do something about it. **This is central point of my writing.**

Then I opened Redux Dev Tools, clicked on my checkbox and saw this:

![image](https://cloud.githubusercontent.com/assets/377261/15871666/ad835452-2caa-11e6-8ebe-c2f3d11c6a2d.png)

That was a moment of "whait a minute..." aha, right since Action Creator uses identity function and I pass it "as-is" to reduce boilerplate to my component event handler it grabs React's synthetic event to it's params, but why it becomes so slow, 400ms for an action dispatch? 

Then I realized that default settings in Redux Dev Tools is to serialize state and that synthetic event object must be huge so serialization of it takes 300-400ms.

If I haven't used Dev Tools I would have not discovered this untill much later when I would be out of context and probably would spend days to figure this out.

So then I figured that default "safe" way to define Action Creators is like this:

`makeActionCreator('Dbg.TOGGLE_BASELINE', () => {})`

It looks a little weird to me, am I missing something? Thanks!

**Comment by timche** [comment]
`onChange` passes an `event` as parameter to the action creator, that's correct.

What you can do instead is writing something like this instead:

```js
<input type="checkbox" onChange={() => props.toggleBaseline}>
```

or

```js
export default connect(state => state.debug, dispatch => ({
  toggleBaseline: () => dispatch(toggleBaseline())
}))(DebugGrid)
```

**Comment by Restuta** [comment]
@timche Yes, but that is not the point, point is that you can easily run into confusing issues (at least I was able to) with this approach. In general this sounds like a trick default behaviour. Did you see a problem at that time when I asked about it in my post?

Also use of arrow functions in there is discouraged https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

**Comment by timche** [comment]
I know that, it was only an example to keep it short ;)

I don't really get your point then, sorry :/ The identity function takes an parameter as payload as it is stated in the docs. What's confusing about this?

**Comment by Restuta** [comment]
@timche I am sorry for not being clear. I tried my best in explanation above and that if you follow normal path with that behaviour it's easy to get into a trap. 

"Normal path" is the following: 

Define action creators => pass action creators to `connect` => call them directly from JSX event handlers => trap

This path looks normal to me, it's recommended path in Redux docs and it leads to a problem, which, presumably a lot of people would not even realize (unless they use Redux Dev Tools). 

I understand that it maybe only me and the rest is doing it just fine and understand everything and stuff =), that's why I tried to ask if you saw a problem back then while reading my comment. If you _did not_ then you part of the community who fell into a trap.

If subjectively this is valid problem, then it requires some attention. I don't want to jump into solutions right away, before we align that it is a potential issue for newcomers. 

Does this make sense?

**Comment by timche** [comment]
Tbh, I don't see an issue with this, because event handlers are working like expected for me personally (or see [here](https://facebook.github.io/react/docs/forms.html#controlled-components)). If anyone should see a problem here as well, then I'm willing to reopen this issue again, otherwise I'll close it for now, if it's okay for you.
