### ISSUE TITLE
Should we use toString() instead of creating constants?

### ISSUE THREAD

**Issue by maxschmeling** [acdlite/redux-actions#93]
With [this line](https://github.com/acdlite/redux-actions/commit/d1aa7d6026e73433808337e10ec03f8df3bd78a6#diff-52ace21827ea0130a413a22cd1697dc8R31) (see below for code) being added to `createAction`, should we use `toString` on the action creator to reference actions instead of creating constants?

```
export default function createAction(type, actionCreator, metaCreator) {
  // code removed for brevity 

  const actionHandler = (...args) => {
    // removed for brevity

    return action;
  };

  // this line is what I'm referring to
  actionHandler.toString = () => type;

  return actionHandler;
}
```

Basically, is there any reason I should be creating and exporting constants for action types, or should I just export action creators, and code that needs to reference the type can just use `myActionCreator.toString()`?

**Comment by timche** [comment]
It's just personal preference. Some prefer constants, others `myActionCreator.toString()`.
