### ISSUE TITLE
[suggestion] createActions: Default action to empty object

### ISSUE THREAD

**Issue by schtauffen** [acdlite/redux-actions#94]
Currently to get a default state from a createActions-returned reducer you must use:

```js
const store = Redux.createStore(
  reducer,
  reducer(undefined, {}),
  Redux.applyMiddleware(logger)
)
```

If the reducer returned by createActions defaulted the action to {}, we can now do:

```js
const store = Redux.createStore(
  reducer,
  reducer(), // yay! no more action.type errors!
  Redux.applyMiddleware(logger)
)
```

**Comment by timche** [comment]
Because Redux is passing `undefined` when initializing the reducer.

[> We’ll start by specifying the initial state. Redux will call our reducer with an undefined state for the first time.](http://redux.js.org/docs/basics/Reducers.html)

**Comment by schtauffen** [comment]
@timche you are correct, Redux takes care of this detail automagically.
