### ISSUE TITLE
Incorrect syntax in the documentation?

### ISSUE THREAD

**Issue by crw** [acdlite/redux-actions#95]
I may just not understand something but this syntax seems to be incorrect:

```
// As parameter in handleAction:
handleAction(increment, {
  next(state, action) {...}
  throw(state, action) {...}
});
```
The second argument is not a legal object in any way I can figure out. I am having a very difficult time understanding how handleAction works to begin with, and this makes it more confusing. Is this a pseudo-code shorthand I just do not recognize? Actual syntax? Future syntax?

I will just add to this, it is fairly clear how you would use createAction and handleActions, but the purpose of handleAction is completely opaque to me. Even if there is some further reading I need to do to understand this, it would be helpful if more of the basic assumptions were outlined in the documentation.

**Comment by timche** [comment]
The syntax is correct, it is part of ES6, [Enhanced Object Literals](https://github.com/lukehoban/es6features#enhanced-object-literals).

**Comment by crw** [comment]
But you need a comma after the first method declaration, yes?

Should I file another bug about providing more documentation context for the purpose behind handleAction?

**Comment by yangmillstheory** [comment]
> But you need a comma after the first method declaration, yes?

Yes.
