### ISSUE TITLE
Add optional behavior to pass payload to reducer

### ISSUE THREAD

**Issue by Lucretiel** [acdlite/redux-actions#98]
I'm not sure how exactly this should be implemented (optional flag?) but it'd be nice if handleAction(s) supported reducers that just take the payload, rather than the whole action object. Reducers very rarely (and, based on my interpretation of the FSA spec, should never) use any part of an action besides they payload (and the type, but only to select which branch of code to use). Basically, I'd like to be able to write:

    handleAction(selectItem, (state, id) => [...state, id], [])

instead of:

    handleAction(selectItem, (state, action) => [...state, action.payload], [])

Any thoughts here? Is this worth pursuing?

**Comment by yangmillstheory** [comment]
I've seen cases where we don't need the entire action, but I think the case of using reducer composition is one where you'd need the entire action object for handoff to a child reducer. 

```js
// here we just need the payload
const items = handleActions({
  [ADD_ITEM](state, { payload: { item } }) {
    return [ ...state, item ]
  },

  [REMOVE_ITEM](state, { payload: { itemId } }) {
    return state.filter(item => item.id !== itemId)
  },
}, [])

const cart = handleActions({
  // boilerplate; see https://github.com/acdlite/redux-actions/issues/31
  [ADD_ITEM](state, action) {
    return { ...state, items: items(state.items, action) }
  },

  [REMOVE_ITEM](state, action) {
    return { ...state, items: items(state.items, action) }
  },
}, {})
```

**Comment by Lucretiel** [comment]
Oh, I've never seen that destructuring syntax before. That pretty much completely takes care of this, thanks!

**Comment by yangmillstheory** [comment]
It's nice. I believe you can destructure arrays from objects too.

```js
let {foo, bar: [ baz, qux = 2 ] } = { foo: 1, bar: [ 'baz' ] }

console.log(foo, baz, qux) // 1, baz, 2
```

**Comment by timche** [comment]
Wow, you guys did a lot of stuff! It will take some time to review it all :O
