### ISSUE TITLE
test-watch fails without running tests if lint fails

### ISSUE THREAD

**Issue by yangmillstheory** [acdlite/redux-actions#99]
```
~/code/private/redux-actions  (feat/create-actions|%=) $ make test-watch
node_modules/.bin/eslint src

/Users/VictorAlvarez/code/private/redux-actions/src/__tests__/createActions-test.js
  36:7  error  Missing semicolon  semi

✖ 1 problem (1 error, 0 warnings)

make: *** [lint] Error 1
```

Is this the right behavior? I feel like linting in `test-watch` should lint once and not fail, or lint continuously.

**Comment by timche** [comment]
Afaik eslint doesn't have any watching capabilities.

**Comment by yangmillstheory** [comment]
Right. We could combine this with `gulp.watch` to achieve the continuous linting behavior.

https://github.com/yangmillstheory/redux-standard-actions/blob/master/gulpfile.babel.js#L83

**Comment by timche** [comment]
I would like to add this feature without implementing a build system.

How about one of these?
- https://www.npmjs.com/package/eslint-watch
- https://www.npmjs.com/package/watch

**Comment by yangmillstheory** [comment]
This issue will be closed by https://github.com/acdlite/redux-actions/pull/107.
